### ISSUE TITLE
建议dubbo-admin做前后台分离和框架改造

### ISSUE THREAD

**Issue by konglz** [apache/dubbo-admin#1]
# 建议dubbo-admin做前后台分离和框架改造

## 3. 建议基于spring security实现登陆和权限控制

* 可以轻松的接入公司内部的SSO体系

## 5. 能否考虑对docker容器的支持，使dubbo-admin能够很easy地打成docker镜像，和配套服务一起部署进容器内

* 配合其他特性，以实现自动化伸缩，是否有可能？

## 6. 基于第4点更进一步，能否提供自动化运维支持，通过暴露一套restful服务，该服务可以查询和操作到dubbo内部，类似elasticsearch的restful接口

* dubbo内部是透明的，一切信息都能够通过api查出来

## 7. 能否提供一些hook，类似git的web hook机制，可以配置一些Lua、Groovy脚本作为是否触发hook的前置filter，在服务状态变化之后，自动推送

* 可以提供一些内置的action

当hook触发之后，可以调到内置action来发邮件、打日志甚至调整服务流量。

## 8. 能否提供文档化支持

* 像swagger那样，在dubbo-admin里集成一套文档系统，这套文档系统还能用于dubbo调试，类似postman

## 9.trace和智能网络节点质量分析

* 像zipkin那样，具备链路跟踪能力，并且能够跟进一步，基于链路跟踪上报的数据，分析出整个服务网路中质量较差的节点，帮助开发发现系统瓶颈所在

**Comment by lovepoem** [comment]
https://github.com/alibaba/dubbo/issues/1252

**Comment by zhaojigang** [comment]
第五点 同时可以提供一个fat-jar，直接以jar包方式启动dubbo-admin也是方便的

**Comment by kimmking** [comment]
We can create a remote team to archieve a new admin-console to do these.

**Comment by madman1990** [comment]
你的建议成功被采纳，就是手册没更新。。坑了一波，哈哈

**Comment by nzomkxia** [comment]
谢谢你的建议，我们目前正在做前后端分离改造，你提到的其他特性也会逐步加上

**Comment by objcoding** [comment]
老哥，这个只是一个控制台，没必要前后端分离吧，而且前后端分离增加了部署工作，基于springboot打个jar包运行就得了，又不是什么大项目，完全没必要。

**Comment by HopeAndStart** [comment]
你的建议成功玩出来了，部署坑了一大波兄弟。哈哈哈

**Comment by sqskg** [comment]
> 你的建议成功玩出来了，部署坑了一大波兄弟。哈哈哈

真的是这样，完全是画蛇添足

**Comment by htynkn** [comment]
1.2.5.8 is done
3 there is a basic one, sso will handle by another issue

 the rest I will create spereate issue if necessary

**Comment by moreasy** [comment]
不知道官方是怎么想的，就几个页面的系统，非要搞个前后端分离，增加了部署成本，而且还做的这么烂，直接拉低dubbo的身段。
