### ISSUE TITLE
Support for group attributes of registry needs to be enhanced in dubbo-ops

### ISSUE THREAD

**Issue by ningyu1** [apache/dubbo-admin#103]
Support for group attributes of registry needs to be enhanced in dubbo-ops.
many users use the registry group for environment isolation, However dubbo-ops seems unable to switch interface information under different groups

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
