### ISSUE TITLE
Dubboctl subsequent enhancement proposals

### ISSUE THREAD

**Issue by DMwangnima** [apache/dubbo-admin#1087]
Based on https://github.com/apache/dubbo-admin/pull/1073, we have implemented manifest generate and manifest install commands. There are some enhancement proposals to make dubboctl more useful.
1. Validate DubboConfig.
2. Implement more intuitive and effective yaml diff method.
3. Add more log statements to locate problems.
4. Implement manifest uninstall and manifest diff commands, profile dump, profile list and profile diff commands.

**Comment by AlbumenJ** [comment]
Agree
