### ISSUE TITLE
关于dubbo-admin配置不生效的问题反映

### ISSUE THREAD

**Issue by ilovedumplings** [apache/dubbo-admin#1091]
### Environment
dubbo-admin image version: 0.5.0
dubbo version 2.7.14

### Steps to reproduce this issue

先配置一个节点的服务为权重为0
![image](https://user-images.githubusercontent.com/19704134/233829660-29f961ec-38e3-4cff-ba5b-7a880eb8f0bd.png)

之后再修改权重为100
![image](https://user-images.githubusercontent.com/19704134/233829693-35863c0d-3288-43d7-b429-88227131cbe1.png)

再次查看服务权重,还是为0 

登陆了zk查看
发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
应该是我使用的不当,但是我没有找到类似的使用问题,请问下是不是dubbo-adamin的版本过高导致的?

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
> 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下

这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知

**Comment by ilovedumplings** [comment]
> > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> 
> 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知

是我的问题,我的配置的语法有些问题。已经解决了,谢谢

**Comment by AZI-D** [comment]
> > > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> > 
> > 
> > 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知
> 
> 是我的问题,我的配置的语法有些问题。已经解决了,谢谢

你好，这个问题你是怎么解决的呢？

**Comment by ilovedumplings** [comment]
> > > > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > > > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> > > 
> > > 
> > > 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知
> > 
> > 
> > 是我的问题,我的配置的语法有些问题。已经解决了,谢谢
> 
> 你好，这个问题你是怎么解决的呢？

我的主要需求是修改应用的权重,然后我是在动态配置页面来搞得,

configVersion: v2.7
enabled: true
configs:
  - side: provider
    addresses:
      - '0.0.0.0:20881'
    parameters:
      weight: 80

我当时是在ip和端口这块映射的时候做错了我记着
address要IP+端口都要写上,或者写0.0.0.0:端口,单独写ip是不生效的。

**Comment by ilovedumplings** [comment]
> > > > > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > > > > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> > > > 
> > > > 
> > > > 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知
> > > 
> > > 
> > > 是我的问题,我的配置的语法有些问题。已经解决了,谢谢
> > 
> > 
> > 你好，这个问题你是怎么解决的呢？
> 
> 我的主要需求是修改应用的权重,然后我是在动态配置页面来搞得,
> 
> configVersion: v2.7 enabled: true configs:
> 
> * side: provider
>   addresses:
>   
>   * '0.0.0.0:20881'
>     parameters:
>     weight: 80
> 
> 我当时是在ip和端口这块映射的时候做错了我记着 address要IP+端口都要写上,或者写0.0.0.0:端口,单独写ip是不生效的。

![image](https://user-images.githubusercontent.com/19704134/237059153-76eb25b3-edc3-4dfc-bd48-25e792b10477.png)

**Comment by AZI-D** [comment]
> 

确实是这样的，多谢多谢

**Comment by AZI-D** [comment]
> > > > > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > > > > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> > > > 
> > > > 
> > > > 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知
> > > 
> > > 
> > > 是我的问题,我的配置的语法有些问题。已经解决了,谢谢
> > 
> > 
> > 你好，这个问题你是怎么解决的呢？
> 
> 我的主要需求是修改应用的权重,然后我是在动态配置页面来搞得,
> 
> configVersion: v2.7 enabled: true configs:
> 
> * side: provider
>   addresses:
>   
>   * '0.0.0.0:20881'
>     parameters:
>     weight: 80
> 
> 我当时是在ip和端口这块映射的时候做错了我记着 address要IP+端口都要写上,或者写0.0.0.0:端口,单独写ip是不生效的。

确实是你说的这样，多谢多谢

**Comment by AZI-D** [comment]
> 



> > > > > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > > > > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> > > > 
> > > > 
> > > > 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知
> > > 
> > > 
> > > 是我的问题,我的配置的语法有些问题。已经解决了,谢谢
> > 
> > 
> > 你好，这个问题你是怎么解决的呢？
> 
> 我的主要需求是修改应用的权重,然后我是在动态配置页面来搞得,
> 
> configVersion: v2.7 enabled: true configs:
> 
> * side: provider
>   addresses:
>   
>   * '0.0.0.0:20881'
>     parameters:
>     weight: 80
> 
> 我当时是在ip和端口这块映射的时候做错了我记着 address要IP+端口都要写上,或者写0.0.0.0:端口,单独写ip是不生效的。

不知道你与没遇到过这个问题：权重调整之后，再次调整不生效的问题（两次调整的时间比较接近）。但是隔一段时间之后再次调整就会生效。

**Comment by AZI-D** [comment]
> 



> > > > > > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > > > > > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> > > > > 
> > > > > 
> > > > > 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知
> > > > 
> > > > 
> > > > 是我的问题,我的配置的语法有些问题。已经解决了,谢谢
> > > 
> > > 
> > > 你好，这个问题你是怎么解决的呢？
> > 
> > 
> > 我的主要需求是修改应用的权重,然后我是在动态配置页面来搞得,
> > configVersion: v2.7 enabled: true configs:
> > 
> > * side: provider
> >   addresses:
> >   
> >   * '0.0.0.0:20881'
> >     parameters:
> >     weight: 80
> > 
> > 我当时是在ip和端口这块映射的时候做错了我记着 address要IP+端口都要写上,或者写0.0.0.0:端口,单独写ip是不生效的。
> 
不知道你遇没遇到过这个问题：权重调整之后，再次调整不生效的问题（两次调整的时间比较接近）。但是隔一段时间之后再次调整就会生效。

**Comment by ilovedumplings** [comment]
> > 
> 
> > > > > > > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > > > > > > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> > > > > > 
> > > > > > 
> > > > > > 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知
> > > > > 
> > > > > 
> > > > > 是我的问题,我的配置的语法有些问题。已经解决了,谢谢
> > > > 
> > > > 
> > > > 你好，这个问题你是怎么解决的呢？
> > > 
> > > 
> > > 我的主要需求是修改应用的权重,然后我是在动态配置页面来搞得,
> > > configVersion: v2.7 enabled: true configs:
> > > 
> > > * side: provider
> > >   addresses:
> > >   
> > >   * '0.0.0.0:20881'
> > >     parameters:
> > >     weight: 80
> > > 
> > > 我当时是在ip和端口这块映射的时候做错了我记着 address要IP+端口都要写上,或者写0.0.0.0:端口,单独写ip是不生效的。
> 
> 不知道你遇没遇到过这个问题：权重调整之后，再次调整不生效的问题（两次调整的时间比较接近）。但是隔一段时间之后再次调整就会生效。

没有遇到过..这个时间是大概多近?你可以看下zk路径下 dubbo/config/dubbo/xxx#config中参数有没有变化,

**Comment by AZI-D** [comment]
> 



> > > 
> > 
> > 
> > > > > > > > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > > > > > > > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> > > > > > > 
> > > > > > > 
> > > > > > > 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知
> > > > > > 
> > > > > > 
> > > > > > 是我的问题,我的配置的语法有些问题。已经解决了,谢谢
> > > > > 
> > > > > 
> > > > > 你好，这个问题你是怎么解决的呢？
> > > > 
> > > > 
> > > > 我的主要需求是修改应用的权重,然后我是在动态配置页面来搞得,
> > > > configVersion: v2.7 enabled: true configs:
> > > > 
> > > > * side: provider
> > > >   addresses:
> > > >   
> > > >   * '0.0.0.0:20881'
> > > >     parameters:
> > > >     weight: 80
> > > > 
> > > > 我当时是在ip和端口这块映射的时候做错了我记着 address要IP+端口都要写上,或者写0.0.0.0:端口,单独写ip是不生效的。
> > 
> > 
> > 不知道你遇没遇到过这个问题：权重调整之后，再次调整不生效的问题（两次调整的时间比较接近）。但是隔一段时间之后再次调整就会生效。
> 
> 没有遇到过..这个时间是大概多近?你可以看下zk路径下 dubbo/config/dubbo/xxx#config中参数有没有变化,

嗯，我再研究研究，我这边改过路径，可能是这个原因

**Comment by AZI-D** [comment]
> 



> > > 
> > 
> > 
> > > > > > > > 发现admin的配置是放在了 /dubbo/com.xxxx.service/configurators 下
> > > > > > > > 然后dubbo 的接口配置是再 /dubbo/com.xxxx.service/provider 下
> > > > > > > 
> > > > > > > 
> > > > > > > 这个逻辑是对的，但是可以看一下服务端日志是不是收到了通知
> > > > > > 
> > > > > > 
> > > > > > 是我的问题,我的配置的语法有些问题。已经解决了,谢谢
> > > > > 
> > > > > 
> > > > > 你好，这个问题你是怎么解决的呢？
> > > > 
> > > > 
> > > > 我的主要需求是修改应用的权重,然后我是在动态配置页面来搞得,
> > > > configVersion: v2.7 enabled: true configs:
> > > > 
> > > > * side: provider
> > > >   addresses:
> > > >   
> > > >   * '0.0.0.0:20881'
> > > >     parameters:
> > > >     weight: 80
> > > > 
> > > > 我当时是在ip和端口这块映射的时候做错了我记着 address要IP+端口都要写上,或者写0.0.0.0:端口,单独写ip是不生效的。
> > 
> > 
> > 不知道你遇没遇到过这个问题：权重调整之后，再次调整不生效的问题（两次调整的时间比较接近）。但是隔一段时间之后再次调整就会生效。
> 
> 没有遇到过..这个时间是大概多近?你可以看下zk路径下 dubbo/config/dubbo/xxx#config中参数有没有变化,

感觉和时间没关系，今早我试了一下没有生效，现在情况是有时候生效有时候不生效
