### ISSUE TITLE
当前前端的几个需求和小调整

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-admin#1110]
1. 删除以下圈中的几个前端菜单
![image](https://github.com/apache/dubbo-admin/assets/18097545/e80c9c27-95c8-4b7d-a822-c512a9cb5175)
2. 服务统计：通过iframe内置grafana页面，grafana地址由后端配置，如果没有可支持弹窗让用户输入
3. 默认首屏设计（周会上共同讨论一下）

**Comment by SDUWYS** [comment]
I will work on this issue.
