### ISSUE TITLE
“条件路由” 创建成功后，弹窗没有自动关闭

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-admin#1117]
![image](https://github.com/apache/dubbo-admin/assets/18097545/80adc1a4-e627-48c5-8a0b-43bca0b98a1e)

**Comment by chickenlj** [comment]
预期应该自动关闭，且关闭后应该主动触发搜索，并显示如下

![image](https://github.com/apache/dubbo-admin/assets/18097545/7931645e-b6be-4648-8a46-d66bc97d46fc)

**Comment by SDUWYS** [comment]
I will work on this issue.
