### ISSUE TITLE
Set default page to display

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-admin#1140]
Visit: localhost:38080/admin/

The default page to display:

![image](https://github.com/apache/dubbo-admin/assets/18097545/ebdaf4c0-a20f-412b-9d06-cfc3846d14cf)

**Comment by chickenlj** [comment]
The contents on this page can be grouped into 4 columns displayed below:

![image](https://github.com/apache/dubbo-admin/assets/18097545/629bb444-1ec7-4030-a9eb-55156b23506d)

**Comment by songxiaosheng** [comment]
先上传一些指标，详细的后续梳理过来
<img width="229" alt="image" src="https://github.com/apache/dubbo-admin/assets/81170548/8e13fcb8-2791-48f9-b83f-f39293b04c5f">

**Comment by songxiaosheng** [comment]
<img width="303" alt="image" src="https://github.com/apache/dubbo-admin/assets/81170548/913a1fa3-d94c-4475-afde-14199df48750">

**Comment by songxiaosheng** [comment]
<img width="350" alt="image" src="https://github.com/apache/dubbo-admin/assets/81170548/1572ae05-ea48-4038-b162-311d015ba774">
