### ISSUE TITLE
Failed to build dubbo project

### ISSUE THREAD

**Issue by GrowOldSeriously** [apache/dubbo-admin#1223]
Problem recurrence：
[ERROR] /D:/.../dubbo-admin-develop/dubbo-admin-develop/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/SwaggerConfiguration.java:[29,52] 找不到符号
[ERROR]   符号:   类 EnableSwagger2
[ERROR]   位置: 程序包 springfox.documentation.swagger2.annotations
[ERROR] /D:/.../dubbo-admin-develop/dubbo-admin-develop/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/config/SwaggerConfiguration.java:[32,2] 找不到符号
[ERROR]   符号:   类 EnableSwagger2

**Comment by chickenlj** [comment]
It's due to an upgrade of the swagger dependency, will be fixed very soon.

**Comment by chickenlj** [comment]
Fixed with https://github.com/apache/dubbo-admin/pull/1226
