### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by nzomkxia** [apache/dubbo-admin#133]

**Comment by lovepoem** [comment]
How about using plaintext in resource files?

**Comment by lovepoem** [comment]
对中文的支持有什么计划么？第一版本应该要支持中文吧？

**Comment by htynkn** [comment]
Currently, all wording is hard code in different vue files.
We need extra them first and then make it easy for community to contribute different language pack files.

**Comment by htynkn** [comment]
close via https://github.com/apache/dubbo-admin/pull/225
