### ISSUE TITLE
能否增加一定的trace支持，以及基于trace搞一些事情?

### ISSUE THREAD

**Issue by konglz** [apache/dubbo-admin#15]
能否增加一定的trace支持，并且能根据trace解决一些问题。

比如说根据trace结果发现循环调用：ServiceA -> ServiceB -> ServiceA，
京东因为循环引用出过一次事情，很短时间内发生了几千万次RPC调用。

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
