### ISSUE TITLE
dubbo ops shows 'Network error'

### ISSUE THREAD

**Issue by Spring8848** [apache/dubbo-admin#169]
i set up dubbo ops as you guy manual
i sign in dubbo admin and search a service via entering the service name.then a alert tips shows a warning-- 'Network error, please check your network settings'
what's wrong with that ? could you help me?thanks

**Comment by nzomkxia** [comment]
please open brower's  `Developer Tools` and check the error

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
