### ISSUE TITLE
[Enhancement] Dubbo monitor enhance machine statistic display and enhance alarm function 

### ISSUE THREAD

**Issue by cvictory** [apache/dubbo-admin#173]
* dubbo监控平台只显示了所有服务端、客户端的整体性能指标，缺少单台机器的指标显示
* dubbo监控平台只能统计平均rt和平均qps，平均值本身就是非常不清晰的指标，采用百分比分布统计的方式会更好
* dubbo监控平台没有提供报警功能，没有办法及时发现问题。或者留一个口子给报警。
------
* The monitoring platform only shows the overall performance indicators of all servers and clients, and the indicator display of a single machine is missing.
* The dubbo monitoring platform can only count the average rt and the average qps. The average value itself is a very unclear indicator. It is better to use the percentage distribution statistics.
* The dubbo monitoring platform does not provide an alarm function, there is no way to find the problem in time. Or leave a hook for the alarm.

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
