### ISSUE TITLE
[dubbo-ops 服务治理策略调整] 不允许禁用(包含只有1个provider)全部服务提供者

### ISSUE THREAD

**Issue by zonghaishang** [apache/dubbo-admin#177]
因为dubbo考虑特殊情况，注册中心推送空列表服务或者计算错误导致no provider:

1.  服务治理，应该控制不允许全量禁用provider
2.  服务治理，应该控制只有1个provider情况下，也不允许禁用。

这2中场景是dubbo内部实现控制机制，主要是保护机制。

**Comment by nzomkxia** [comment]
嗯，这个可以在提交路由规则的时候，做一下计算。

**Comment by zonghaishang** [comment]
要考虑权重调节的场景， 负责均衡只对>=3个provider生效， <3台provider设置权重不会生效

**Comment by nzomkxia** [comment]
为什么只对>=3台生效？

**Comment by zonghaishang** [comment]
1. 如果只有2台会退化成轮训，不调用负载均衡
2. 如果只有1台，直接返回，不调用负载均衡

**Comment by nzomkxia** [comment]
负载均衡和权重是两码事吧

**Comment by zonghaishang** [comment]
3台以上，权重0的服务不会有流量进来

**Comment by carryxyh** [comment]
dubbo issue list里的相关issue
https://github.com/apache/incubator-dubbo/issues/428
https://github.com/apache/incubator-dubbo/issues/608
https://github.com/apache/incubator-dubbo/issues/645
https://github.com/apache/incubator-dubbo/issues/2550 （禁用的provider如果在一个group中好像也有一些问题）

**Comment by majinkai** [comment]
实际上有很多场景都可能导致provider个数为0，比如设置了黑名单、隔离机房等等治理，这样去禁用某个provider，也会造成某些consumer对应的provider个数变为0

**Comment by zonghaishang** [comment]
这块可以统一整理下，在dubbo-ops里面控制

**Comment by nzomkxia** [comment]
最后都会归结到路由规则和动态配置这两个，提交规则的时候计算一下应该可以

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.

**Comment by ldj19951109** [comment]
dobbo-admin
这个怎么一堆问题？ 禁用开关不生效，我在本地起2个服务，一个供给者一个消费者，结果出现3个供给者，分别是2个消费者，和1个真正的供给者
![image](https://github.com/apache/dubbo-admin/assets/94091079/ac460bd8-a09c-44d5-adc7-bdbfab49c911)
