### ISSUE TITLE
incubator-dubbo-ops后台启动不报错，搜索服务又不见了

### ISSUE THREAD

**Issue by qiudaozhang** [apache/dubbo-admin#184]
启动项目，项目并没有报错，zookeeper可以通过客户端
`
ls /dubbo
`
看到服务，但是在后台项目访问搜索xxx.xxx.HelloService，无法看到结果，响应结果为[]，console并没显示错误，之前这个问题没有了的，clone了最新的项目又出现了这种情况。

**Comment by nzomkxia** [comment]
服务有提供者在运行么？

**Comment by majinkai** [comment]
项目默认连接的是127.0.0.1:2181，你看一下是不是连错了zk

**Comment by qiudaozhang** [comment]
> 在运行么？

在运行，zookeeper里面是能通过ls查看到的。

**Comment by qiudaozhang** [comment]
> 连接的是127.0.0.1:2181，你看一下是不是连错了zk

我在zookeeper所在服务器启动管理项目一样搜不到，windows环境下测试也搜不到。只有zookeeper命令可以查询到。

**Comment by nzomkxia** [comment]
你试一下搜索 * 看看有没有结果？还有zk的组别有改过么？

**Comment by Hojunwei** [comment]
同问。启动不报错，服务从zk看到有的

**Comment by vincentlxl** [comment]
我的启动不了啊，老是报创建bean失败

**Comment by hoofungson** [comment]
服务提供者搜索"*"看看有没有，新版dubbo-admin搜索方面不是很好用。

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
