### ISSUE TITLE
I hope [weight adjustment] can search by ip

### ISSUE THREAD

**Issue by manzhizhen** [apache/dubbo-admin#185]
In fact, the old version of dubbo admin can query all related services through ip, and then make weight adjustments (bulk multiple weight, batch semi-weight) for the batch service. This function is especially useful for the "Sentinel Machine", I hope to support it, thank you!

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
