### ISSUE TITLE
dynamic config client

### ISSUE THREAD

**Issue by nzomkxia** [apache/dubbo-admin#189]
目前dubbo2.7中的`DynamicConfiguration`只有读操作，没有写操作，Ops需要自己实现一个，向配置中心做数据写入和读取。

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
