### ISSUE TITLE
java.util.regex.PatternSyntaxException: Unmatched closing ')'

### ISSUE THREAD

**Issue by gMan1990** [apache/dubbo-admin#19]
https://github.com/apache/incubator-dubbo-ops/blob/158ee09ef91c7a39d13678a8035a3e076877f942/dubbo-admin/src/main/java/com/alibaba/dubbo/governance/web/common/interceptor/RestfuleUrlRewriter.java#L176

with
- oldPath: /sysinfo/logs/rootContextPath.getURI("/sysinfo/logs")
- method: logs")

on url: http://127.0.0.1:8080/sysinfo/logs/change?level=WARN

**Comment by ralf0131** [comment]
Hi, welcome!

Thanks for reporting this issue.
Would you please send a pull request?

**Comment by gMan1990** [comment]
<img width="514" alt="wx20180401-103849 2x" src="https://user-images.githubusercontent.com/5050994/38169294-f5082b1a-3598-11e8-9244-29113b594b8a.png">

i don't know how to fix it...2333333
