### ISSUE TITLE
原来老版本功能是否已经完善

### ISSUE THREAD

**Issue by ruterfu** [apache/dubbo-admin#195]
新版中api中, 原来老版本原有功能已经实现了吗, 还是没有完全实现(新版本中用户部分不算.), 如果页面没有完全实现, 那api中实现了吗.

**Comment by majinkai** [comment]
新版本会合并一些api，现有的api基本已经覆盖到了原有的功能，目前正在处理dubbo2.7相关的一些功能，我们会根据社区用户的需要不断完善，后续会将monitor功能整合进来

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
