### ISSUE TITLE
multi registry support

### ISSUE THREAD

**Issue by rrfeng** [apache/dubbo-admin#198]
Any idea?

**Comment by chickenlj** [comment]
请问你关于多注册中心的使用场景是？

What's your scenario for the requirement of multi registries? Could you please describe in more details, so the Dubbo team can better meet your requirement.

**Comment by rrfeng** [comment]
@chickenlj 
我们在多环境（online/staging/dev）多集群（cn/us/eu）等都是通过不同注册中心（zookeeper）来实现的，这样我们必须在每个注册中心部署一个对应的 dubbo-admin 来分别管理。
于是很自然的希望一个管理平台可以直接管理多个注册中心。

**Comment by nzomkxia** [comment]
谢谢，这个特性我们后续会做支持

**Comment by nzomkxia** [comment]
目前的想法是：
* 支持在`application.properties`或者配置中心配置多个注册中心的地址
* 服务查询的页面，合并多个注册中心的查询结果，并且标明来源
* 服务详情的页面，合并多个注册中心的服务提供者，并且标明提供者来源
* 服务治理，在Dubbo2.6的兼容逻辑中，写多个注册中心

**Comment by kezhenxu94** [comment]
> 目前的想法是：
> 
> * 支持在`application.properties`或者配置中心配置多个注册中心的地址
> * 服务查询的页面，合并多个注册中心的查询结果，并且标明来源
> * 服务详情的页面，合并多个注册中心的服务提供者，并且标明提供者来源
> * 服务治理，在Dubbo2.6的兼容逻辑中，写多个注册中心

@nzomkxia 多注册中心使用场景如 @rrfeng 所说, 一般用于区分环境, 如果按照你的说法, 就是把不同环境的各个服务混合展示到一起了, 实际应用中应该不会想要这样操作吧(增大误操作的概率)?
所以是否可以提供一个全局的切换环境的操作(例如在语言切换按钮附近添加一个环境切换按钮, 可以选择配置的多个注册中心中的某一个)? 不知道这样是否达到需求 @rrfeng

**Comment by rrfeng** [comment]
@kezhenxu94  整体切换的方式更符合直觉一些。

**Comment by nzomkxia** [comment]
@rrfeng @kezhenxu94
* 整体切换的方式，适用于两个环境不通的时候，比如线上和线下，现在ops的api里面，预留了一个环境的字段，可以用来区分 ，这个属于多环境 
* 这个issue里面，多注册中心指的是从多个registry center拿到服务，然后展示到一起，当然展示的时候可以通过标识来区分环境  
* 只有注册中心需要多个，配置和元数据都不需要，保持和Dubbo核心的行为一致
* 多个环境的问题再另外考虑

**Comment by sunbufu** [comment]
@nzomkxia 我们这边有这么个应用场景，zk 集群按照部署环境区分为 开发、测试、预览和生产，同时不同的业务线划分不同的 group。

**Comment by CodingSinger** [comment]
已经支持了吗

**Comment by KeRan213539** [comment]
这个目前已列入计划,不过实际实现可能与大家讨论的略有不同

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
