### ISSUE TITLE
Issues on weight adjust module

### ISSUE THREAD

**Issue by wolf427** [apache/dubbo-admin#200]
1.The updateId keeps available after executing a put request. It will cause a bug like update a record on create dialog after doing an update operation.
2.The create dialog will not automatically close after getting server response. Because the http status code is 201.
3.The post request get wrong weight parameter

**Comment by nzomkxia** [comment]
thanks, is it happened on `develop` branch?

**Comment by wolf427** [comment]
实际上还有一个bug
对于已经有的记录，修改的时候ip不会保存，会变成0.0.0.0。但是因为在修改的时候可以填入多个IP，而权重记录是一个ip一条单独的记录，我不知道你们预期的设计是什么，所以就没有修复这个bug。

google translate:
There exist actually another bug
For existing records, the ip will not be saved when it is modified, it will become 0.0.0.0. But because you can fill in multiple IPs when you modify it, and the weight record is a separate record of ip, I don't know what design you are expecting, so I didn't fix this bug.

**Comment by nzomkxia** [comment]
I've comment your pr, please make a tiny change and I can merge it

**Comment by nzomkxia** [comment]
> 实际上还有一个bug
> 对于已经有的记录，修改的时候ip不会保存，会变成0.0.0.0。但是因为在修改的时候可以填入多个IP，而权重记录是一个ip一条单独的记录，我不知道你们预期的设计是什么，所以就没有修复这个bug。
> 
> google translate:
> There exist actually another bug
> For existing records, the ip will not be saved when it is modified, it will become 0.0.0.0. But because you can fill in multiple IPs when you modify it, and the weight record is a separate record of ip, I don't know what design you are expecting, so I didn't fix this bug.

I'll look into it, thanks

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
