### ISSUE TITLE
关于dubbo-ops更新计划的咨询

### ISSUE THREAD

**Issue by sunbufu** [apache/dubbo-admin#205]
hi，我们计划使用dubbo-ops，但是最近看到好像还没有开发完成，有些功能还尚不完善，我想问下咱这边有什么开发计划吗？已经如何参与到开发中呢？

**Comment by nzomkxia** [comment]
目前的服务搜索和服务治理的功能都已经开发完成，配合Dubbo 2.7版本中的标签路由，应用维度的服务治理也已经完成，这里有demo：http://47.91.207.147/#/service 请问你们还有什么功能需求？可以提issue。  
接下来的开发主要是服务测试和metrics这两个功能，参与开发，可以看下目前Issue上面的一些问题和功能点

**Comment by noryar1** [comment]
例如统计和流量监控相关的功能，都会在Metrics里面吗？这个模块的开发计划是什么样的呀？

**Comment by sunbufu** [comment]
我也觉得可以添加一些 monitor 的功能。

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
