### ISSUE TITLE
Nacos注册中心支持

### ISSUE THREAD

**Issue by lmhongwei** [apache/dubbo-admin#206]
什么时候可以支持Nacos注册中心呢？

**Comment by mercyblitz** [comment]
Recently,  https://github.com/dubbo/dubbo-registry-nacos has supported as Nacos registry, You just need to add this dependecies into your project, and the application will be displayed on Ops console, however, it's still not supported to adjust weight of load-balance for Dubbo's services, you have to official integartion.

**Comment by DaveRoey** [comment]
don't understand

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
