### ISSUE TITLE
Add SSO integration support

### ISSUE THREAD

**Issue by htynkn** [apache/dubbo-admin#210]
Dubbo-admin should support different auth ways.

Many company use Okta or other identity service to do auth, most of them are support strandard SSO. I suggest dubbo-admin to provide SSO config so user can easily integration with their own identity service.

Another suggestion is LDAP(https://github.com/apache/incubator-dubbo-ops/issues/85) which is also famous solution for auth, may be consider them in next version.

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
