### ISSUE TITLE
Need more information about new configurations

### ISSUE THREAD

**Issue by htynkn** [apache/dubbo-admin#213]
from https://github.com/apache/incubator-dubbo-ops/issues/150

> 新版本里面关于配置的部分说明不够。

> 里面的几个配置项新增的分别是做什么用的？
> dubbo.registry.group=dubbo
> dubbo.configcenter=zookeeper://127.0.0.1:2181
> dubbo.apollo.token=e16e5cd903fd0c97a116c873b448544b9d086de9
> dubbo.apollo.appId=test
> dubbo.apollo.env=dev
> dubbo.apollo.cluster=default
> dubbo.apollo.namespace=dubbo

> 问题：
> 1、生产用application-production.properties，开发用application.properties这个吗？
> 2、dubbo.configcenter是不是应该写成dubbo.config.center？
> 3、后面dubbo.apollo相关的项可以不用吗？分别是做什么用？

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
