### ISSUE TITLE
Github Action supported to auto-deploy the live demo

### ISSUE THREAD

**Issue by lovepoem** [apache/dubbo-admin#215]
I think Github Action should be supported to auto-deploy the demo 

If a pr is merged ,we can see the change from the online demo
>Demo Address
http://47.91.207.147/#/service
this demo is the latest version of develop branch, you can try it before building from source code

**Comment by nzomkxia** [comment]
good advice, now I'm deploying this mannually

**Comment by lovepoem** [comment]
@htynkn , can this be finished with Jenkins CI of Apache  ?

**Comment by htynkn** [comment]
where is this server?  how current manual deployment works?

**Comment by htynkn** [comment]
there is no active server now.
I'm thinking with below way:
1.github action trigger a integration test to do basic function verify (we have a login function check now)
2.publish dubbo-admin docker image and some demo provider and consumer docker image to github packages
3.prepare a docker-compose file
4.add this file to play-with-docker

then anyone with dockerhub account can easliy start a mini 'cluster‘ to try live demos

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
