### ISSUE TITLE
Test case should be added to enhance the test coverage 

### ISSUE THREAD

**Issue by lovepoem** [apache/dubbo-admin#216]
Test case should be added to enhance the test coverage 
1. backend testcase
2. frontend testcase

**Comment by manaswinidas** [comment]
Is this project using any framework for testing?

**Comment by lovepoem** [comment]
Backend  framework for testing , I think is the  same as [Dubbo](https://github.com/apache/incubator-dubbo) : junit, mockito and so on

Frontend use Vuejs  @nzomkxia ， can you give some specifications?

**Comment by nzomkxia** [comment]
@manaswinidas thank you for your interesting in this project.
frontend unit testing, I think we can get a refer to Vue official cookbook: https://vuejs.org/v2/cookbook/unit-testing-vue-components.html

**Comment by biyuhao** [comment]
I'm on it. First I will bring YamlParserTest back (#227)

**Comment by kezhenxu94** [comment]
Hi @nzomkxia , I'm interested in the project too and I just create some integration tests, and I'm wondering  which branch should I open the Pull Request to? The `develop` branch or `master` or `service-test`?
