### ISSUE TITLE
Will the old version dubbo-admin be maintained in this project ?

### ISSUE THREAD

**Issue by lovepoem** [apache/dubbo-admin#217]
Will the old version dubbo-admin be maintained in this project ?
If so, how to maintain it? create a new branch ?

**Comment by nzomkxia** [comment]
Since the new version will be compatibility with Dubbo2.6, I'm not planning to maintain the over version of dubbo admin

**Comment by nzomkxia** [comment]
> @nzomkxia 你好! 我一直关注dubbo-ops,同事感谢你的付出.
> 
> 我的问题是dubbo monitor.
> 
> * 有关dubbo monitor有什么开发计划?
> * dubbo monitor是否有实现方案?
> * 如何贡献代码给dubbo-ops?

* dubbo monitor会结合在当前版本Dubbo Ops中，左边的菜单栏已有入口
* dubbo monitor会基于即将开源的dubbo metrics来做数据采集  
* 贡献代码可以从解决已有的issue开始

**Comment by lovepoem** [comment]
get it
