### ISSUE TITLE
i18n support translation

### ISSUE THREAD

**Issue by nzomkxia** [apache/dubbo-admin#218]
I've add i18n support with [vue-i18n](https://github.com/kazupon/vue-i18n) in `i18n` branch, and the https://github.com/apache/incubator-dubbo-ops/blob/i18n/dubbo-admin-frontend/src/lang/zh.js file need to be translated into Chinese

**Comment by chenzhiguo** [comment]
OK, let me do it.

**Comment by lovepoem** [comment]
Are there any backend prompt words?  Can that be configured in the resource file?

**Comment by nzomkxia** [comment]
> Are there any backend prompt words? Can that be configured in the resource file?

yes, the exception message are backend prompt words, I'll deal it with spring resource files

**Comment by lovepoem** [comment]
> yes, the exception message are backend prompt words, I'll deal it with spring resource files

If the wiki can tell how to configure words in the  frontend and  backend resource files , I think many nature languages will be quickly configured

**Comment by nzomkxia** [comment]
> > yes, the exception message are backend prompt words, I'll deal it with spring resource files
> 
> Nice ! If the wiki can tell how to configure words in the frontend and backend resource files , I think many kinds of nature languages will be quickly configured

I'll build a backend framework to support i18n first, and write a document about how it works and how to contribute

**Comment by ravencoo** [comment]
How to solve the problem... `[ERROR] Failed to execute goal on project dubbo-admin-backend: Could not resolve dependencies for project org.apache:dubbo-admin-backend:jar:0.0.1-SNAPSHOT: Could not find artifact org.apache.dubbo:dubbo:jar:2.6.5 in nexus-aliyun (http://maven.aliyun.com/nexus/content/groups/public) -> [Help 1]`

**Comment by htynkn** [comment]
Closing via #218
