### ISSUE TITLE
Add a graph to display the call relationship of  all applications

### ISSUE THREAD

**Issue by lovepoem** [apache/dubbo-admin#23]
Add a global diagram. Display the call relationship of all applications

1. Select a good front end graph component
2. Good front end interaction

**Comment by kezhenxu94** [comment]
Will you consider using [Echarts](https://github.com/apache/incubator-echarts) in this project?

**Comment by lovepoem** [comment]
Closed via https://github.com/apache/dubbo-admin/pull/437
