### ISSUE TITLE
IP clearance status

### ISSUE THREAD

**Issue by ralf0131** [apache/dubbo-admin#284]
As of January 31st, 2019, the latest status is as follows:

| contributor                                     | commits | Lines changed          | contribution | Employer         | ASF ICLA signed? | Apache Dubbo Committer? | Contribution since join ASF? |
| ----------------------------------------------- | ------- | ---------------------- | ------------ | ---------------- | ---------------- | ----------------------- | ---------------------------- |
| [nzomkxia](https://github.com/nzomkxia)         | 211     | 136,980 ++  133,406 -- | Too much     | Alibaba          | Yes              | Yes                     | Yes                          |
| [majinkai](https://github.com/majinkai)         | 30      | 1,939 ++  786 --       | Too much     | Handuyishe       | Yes              | Yes                     | Yes                          |
| [beiwei30](https://github.com/beiwei30)         | 29      | 393 ++  24,109 --      | Too much     | Alibaba          | Yes              | Yes                     | Yes                          |
| [lovepoem](https://github.com/lovepoem)         | 14      | 1,236 ++  794 --       | Too much     | Weidian          | Yes               | Yes                     | Yes                          |
| [chickenlj](https://github.com/chickenlj)       | 13      | 37,333 ++  1,447 --    | Too much     | Alibaba          | Yes              | Yes                     | No                           |
| [kezhenxu94](https://github.com/kezhenxu94)     | 8       | 1,079 ++  250 --       |  code style plugin           |           Li Zhi       | No               | No                      | Yes                          |
| [biyuhao](https://github.com/biyuhao)           | 8       | 786 ++  137 --         |      maven wrapper & unit test        | Asiainfo-sec     | Yes              | No                      | Yes                          |
| [chenzhiguo](https://github.com/chenzhiguo)     | 8       | 699 ++  143 --         |    i18n support          | Jingdong         | No               | No                      | Yes                          |
| [sunbufu](https://github.com/sunbufu)           | 5       | 626 ++  16 --          |    unit test          |                  | No               | No                      | Yes                          |
| [wolf427](https://github.com/wolf427)           | 4       | 336 ++  81 --          |     input prompt & unit test         |                  | No               | No                      | Yes                          |
| [kimmking](https://github.com/kimmking)         | 4       | 29 ++  2 --            |      Trivial        | Rongguan         | Yes              | Yes                     | Yes                          |
| [hrsstd](https://github.com/hrsstd)             | 3       | 179 ++  86 --          |   codestyle & unit test           |      Netease            | No               | No                      | Yes                          |
| [qq925716471](https://github.com/qq925716471)   | 2       | 46 ++  12 --           |       Trivial       |                  | No               | No                      | Yes                          |
| [manaswinidas](https://github.com/manaswinidas) | 1       | 1 ++  1 --             | Trivial      |                  | No               | No                      | Yes                          |
| [ujjboy](https://github.com/ujjboy)             | 1       | 2 ++  2 --             |         Trivial     |                  | No               | No                      | Yes                          |
| [sinelu](https://github.com/sinelu)             | 1       | 2 ++  1 --             |     Trivial         |                  | No               | No                      | Yes                          |
| [ShuaiJunlan](https://github.com/ShuaiJunlan)   | 1       | 2 ++  2 --             |       Trivial       |                  | No               | No                      | Yes                          |
| [huadong](https://github.com/huadong)           | 1       | 24 ++  7 --            |       Trivial       |                  | No               | No                      | Yes                          |
| [qingdengyue](https://github.com/qingdengyue)   | 1       | 829 ++  2 --           |   i18n           |                  | No               | No                      | Yes                          |
| [realhj](https://github.com/realhj)             | 1       | 3 ++  0 --             |        Trivial      |                  | No               | No                      | Yes                          |
| [htynkn](https://github.com/htynkn)             | 1       | 3 ++  1 --             |    Trivial          | Meituan-Dianping | Yes              | Yes                     | Yes                          |
| [giraffe8](https://github.com/giraffe8)         | 1       | 1 ++  1 --             |      Trivial        |                  | No               | No                      | Yes                          |
| [ralf0131](https://github.com/ralf0131)         | 1       | 11 ++  0 --            | Trivial      | Alibaba          | Yes              | Yes                     | Yes                          |

Most of the contributions are made after this project has been transferred to ASF.

There are only 1 contributors who made contribution before the transfer, which is chickenlj and is Dubbo PPMC.

@nzomkxia Could you please summarize the contribution of the contributors, you can update the contribution column.

Overall I think there is nothing we need to do further.

**Comment by nzomkxia** [comment]
@ralf0131  the contribution table has been updated

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
