### ISSUE TITLE
Split the i18n language file to individual files as per different modules

### ISSUE THREAD

**Issue by kezhenxu94** [apache/dubbo-admin#294]
I suggest splitting the i18n language file to individual files acccording to different modules, because:

- there are chances that different messages with same key are required in different modules

- it would be more contextual for people who wants to localize to their language

@nzomkxia WDYT? If it's good, I'll open another issue.

_Originally posted by @kezhenxu94 in https://github.com/apache/incubator-dubbo-ops/pull/286#issuecomment-459646290_

**Comment by kezhenxu94** [comment]
I can do this

**Comment by nzomkxia** [comment]
Thanks, please create a pr
