### ISSUE TITLE
Could dubbo provide some annotations to describe service, method, parameter info in meta-data?

### ISSUE THREAD

**Issue by zhaixiaoxiang** [apache/dubbo-admin#309]
In service test, we can't know the descriptions of the service, method, parameter. 

Following is the current, there are not descriptions of service, method, parameter...
![image](https://user-images.githubusercontent.com/11908486/52933934-f1b4ab00-338f-11e9-8a84-aab5197351e6.png)

This is souche's Dubbo Admin, there  are descriptions, could we add this function?
![image](https://user-images.githubusercontent.com/11908486/52933866-a69a9800-338f-11e9-959c-bf49c6a14783.png)

**Comment by zhaixiaoxiang** [comment]
I will PR A.S.A.P

**Comment by sunbufu** [comment]
Hello, I have a question about this. How can we get descriptions? Do we need extra annotation？

**Comment by KeRan213539** [comment]
Please refer to [dubbo-api-docs](https://dubbo.apache.org/zh/blog/2020/12/22/dubbo-api-docs-apache-dubbo%E6%96%87%E6%A1%A3%E5%B1%95%E7%A4%BA%E6%B5%8B%E8%AF%95%E5%B7%A5%E5%85%B7/)
