### ISSUE TITLE
There are some redundant  data in /dubbo/metadata/*/service.data

### ISSUE THREAD

**Issue by zhaixiaoxiang** [apache/dubbo-admin#310]
- Some types are resolved more than once.
- Like Integer, String, Long and so on, these type should not be resolved. Meaningless!

![image](https://user-images.githubusercontent.com/11908486/52934121-7b647880-3390-11e9-82de-b5e6c51e9b64.png)

**But, I don't know whether we could optimize these since there maybe someone already use these data structures**

**Comment by zhaixiaoxiang** [comment]
I will PR A.S.A.P

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
