### ISSUE TITLE
dubbo-ops建议内置MonitorService服务

### ISSUE THREAD

**Issue by linzhiqiang0514** [apache/dubbo-admin#319]
duub-ops建议内置MonitorService服务，可以采集现有的监控数据，并展示。
另外，dubbo端的监控数据，希望可以指定特殊端口，并允许配置采用Rest服务采集，也方便第三方应用接入。

也可以将客户端对应的monitor客户端改造为推送的时候，不止往dubboMonitor推送，也可以往其他的第三方Rest服务推送。

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
