### ISSUE TITLE
现有的ops界面，对比原来的admin界面，部分参数不展示了。

### ISSUE THREAD

**Issue by linzhiqiang0514** [apache/dubbo-admin#320]
对比以前的dubbo-admin，部分参数看不到了。
如：pid,timeout参数等。

![qq20190225-112819](https://user-images.githubusercontent.com/8164566/53312566-8c613c80-38f0-11e9-98d4-fc7e5672e8f8.png)

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
