### ISSUE TITLE
Health check endpoint ?

### ISSUE THREAD

**Issue by htynkn** [apache/dubbo-admin#330]
Do we have health check endpoint for dubbo-ops?

Something like host/health and return 
```json
{
   "status": "UP"
}
```

I think this is useful for system to do monitor and health check

**Comment by nzomkxia** [comment]
do you mean service health check like this: 
![admin4](https://user-images.githubusercontent.com/1183397/53928039-a73b6a00-40c3-11e9-861b-678718d25117.png)

**Comment by htynkn** [comment]
> do you mean service health check like this:
> ![admin4](https://user-images.githubusercontent.com/1183397/53928039-a73b6a00-40c3-11e9-861b-678718d25117.png)

yes

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
