### ISSUE TITLE
用springboot stater提供provider有问题错误如下， 用dubbo-provider.xml配置没有问题可以正常用dubbo admin测试接口

### ISSUE THREAD

**Issue by partys88** [apache/dubbo-admin#339]
![image](https://user-images.githubusercontent.com/13522975/54799377-e35ff480-4c97-11e9-9e7c-c2cff23e7170.png)
![image](https://user-images.githubusercontent.com/13522975/54799449-45b8f500-4c98-11e9-9a50-d521c59f9e4c.png)

**Comment by kexianjun** [comment]
pls upload your images again

**Comment by hoofungson** [comment]
重新上传你异常图片

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
