### ISSUE TITLE
[Proposal] 服务治理规则在服务/应用不存在时，仍然可以维护。

### ISSUE THREAD

**Issue by lexburner** [apache/dubbo-admin#349]
![image](https://user-images.githubusercontent.com/11485990/55135907-e5c6c080-5167-11e9-8666-0b04487cb906.png)

以上图新增标签路由为例，当应用名不存在时，提示无法保存规则。看了一下源码，标签路由会校验服务使用的 Dubbo 版本是否为 2.7，因为只有 2.7 支持 Dubbo-Admin 的标签路由服务治理规则。但强校验版本，会导致应用中没有服务或应用下线时无法对规则进行维护，这似乎不太合理。

建议对于服务治理规则和应用配置不需要校验应用和服务是否存在，因为可能是即将发布的服务、应用，管理者想要事先在控制台配置规则。

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
