### ISSUE TITLE
dubbo-admin-ui 编译失败  Could not extract the Node archive: Could not extract archive: 

### ISSUE THREAD

**Issue by clark4working** [apache/dubbo-admin#351]
dubbo-admin-ui 编译失败  Could not extract the Node archive: Could not extract archive:

**Comment by nzomkxia** [comment]
完整的错误截图看一下

**Comment by hiwjd** [comment]
我也碰到了这个问题，执行`mvn clean package`的末尾一段截图：
![image](https://user-images.githubusercontent.com/1838262/56182906-ca542480-6046-11e9-80c0-156747f98e9d.png)

**Comment by kezhenxu94** [comment]
试试把这个文件删除重新运行试试

![image](https://user-images.githubusercontent.com/15965696/56183251-531f9000-6048-11e9-9d3b-d295414fad2a.png)

**Comment by hiwjd** [comment]
是的，删除后重新执行可以了。之前的node安装文件不完整。感谢🙏

**Comment by clark4working** [comment]
OK ，知道了 是这个 包下载不全，有可能是 网络传输导致的 数据丢失 ，我尝试通过其他方式解决吧 ，多谢

min <notifications@github.com> 于2019年4月10日周三 下午1:48写道：

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
