### ISSUE TITLE
别的模块可以正常调用我的rpc接口用dubboadmin测试工具不能调通。

### ISSUE THREAD

**Issue by partys88** [apache/dubbo-admin#353]
别的模块可以正常调用我的rpc接口用dubboadmin测试工具不能调通。
![image](https://user-images.githubusercontent.com/13522975/55308695-12434b00-548e-11e9-9c73-fc5349f76a55.png)

**Comment by nzomkxia** [comment]
@partys88 显示的是没有服务提供方，有没有配置规则之类的？

**Comment by ymingxu** [comment]
我也遇到了这个问题。没有配置任何规则，不知道是什么问题

**Comment by nzomkxia** [comment]
@partys88 @ymingxu 能不能提供一个可以复现的demo

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
