### ISSUE TITLE
dubbo-admin-ui: 方法测试页面编辑器模式选择“code”时，编辑器样式错位

### ISSUE THREAD

**Issue by Frederick-S** [apache/dubbo-admin#358]
如图：
<img width="481" alt="捕获" src="https://user-images.githubusercontent.com/1182395/55681842-a8c7ae80-595d-11e9-99fe-a03df1c3c1ac.PNG">

**Comment by nzomkxia** [comment]
@Frederick-S 我这里无法复现，能提供下具体的浏览器类型么？

**Comment by Frederick-S** [comment]
@nzomkxia Chrome 74.0.3729.131 (Official Build) (64-bit).

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
