### ISSUE TITLE
当远程方法入参是Map<String,Object>类型时，只要包含Map类型时，测试不通过。

### ISSUE THREAD

**Issue by ycx901221** [apache/dubbo-admin#362]
跟踪代码时发现admin在远程调用方法时，从元数据中心获取的参数类型就是"Map<String,Object>"，此类型在Provider端解析不了(只能解析形如Map[][]格式)。在不改变dubbo源码的情况下，我暂时在admin远程调用方法前去掉了<>，也就是将类型改为“Map”，才可以调用成功，希望下个迭代更新下这个Bug。

**Comment by nzomkxia** [comment]
提个PR？

**Comment by sunbufu** [comment]
Hi，我添加了一点代码，在调用 `genericService.$invoke()` 之前，把参数类型 `parameterTypes` 的范型标志擦出掉了，辛苦帮忙 review 下，感谢。
