### ISSUE TITLE
部署包优化

### ISSUE THREAD

**Issue by shalousun** [apache/dubbo-admin#364]
内否对admin打包结构做下优化，方便部署和修改配置。例如这种结构：
```
├─bin
│      setenv.sh
│      start.bat
│      start.sh
│      stop.sh  
├─config
│      application.properties
│      logback-spring.xml
│─dubbo-admin-0.1.jar
```

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
