### ISSUE TITLE
We cannot ship the LGPL library in Apache Products

### ISSUE THREAD

**Issue by WillemJiang** [apache/dubbo-admin#366]
I just checked the binary release kit, it has the third party dependency of LGPL (Hibernate core) which is belonged to [Cataloge X](https://www.apache.org/legal/resolved.html#category-x),  it cannot be included in Apache Product.
We could fix it by using EclipseLink, you don't need to change the JPA codes.

**Comment by justinmclean** [comment]
Is this an optional dependancy?

**Comment by nzomkxia** [comment]
@WillemJiang the Hibernate serial we use is under LGPL only, there's no EcpliseLink for it:  https://github.com/hibernate/hibernate-orm/tree/5.2.7   
@justinmclean  this is an indirect dependency imported by spring boot web, only appears in binary release

**Comment by WillemJiang** [comment]
[EclipseLink](https://www.eclipse.org/eclipselink/) is another JPA implementation, which could be used in Apache product.  We cannot use LGPL library in Apache product.

**Comment by KeRan213539** [comment]
We will fix this before the next release
