### ISSUE TITLE
监控中心

### ISSUE THREAD

**Issue by 616341846** [apache/dubbo-admin#375]
目前版本是不是没有支持监控中心的功能？我怎么找不到对应的监控功能呢 谢谢

**Comment by nzomkxia** [comment]
监控功能会基于dubbo核心集成的metrics，正在开发中，预计这两天会把代码合进去，谢谢关注

**Comment by Alan000** [comment]
期待ing

**Comment by zlm900125** [comment]
目前是什么进展呢？

**Comment by wangjw1989** [comment]
同求进展

**Comment by nevin9939** [comment]
+1  ？？？

**Comment by lisan04** [comment]
请问下，目前该功能进展如何？

**Comment by ArtificialIdoit** [comment]
> 监控功能会基于dubbo核心集成的metrics，正在开发中，预计这两天会把代码合进去，谢谢关注

问一下，现在可以用了吗？

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
