### ISSUE TITLE
2.7 以后dubbo-admin 怎么禁用服务

### ISSUE THREAD

**Issue by jeefgit** [apache/dubbo-admin#377]
2.7 以后dubbo-admin 怎么禁用服务？dubbo源码没看出用什么方式禁用服务，2.6通过override，2.7显然已经过滤了这个URL

**Comment by nzomkxia** [comment]
目前版本的dubbo admin没有提供禁用的功能

**Comment by shaofei007** [comment]
dubbo本身如果一个服务需要被禁用，在zookeeper里面会有字段标识的吧？

**Comment by jeefgit** [comment]
disable属性？通过admin去增加这个属性？我记得在发布的时候可以设置这个属性

**Comment by icom2014** [comment]
动态配置里这样做？
---
scope: application
key: demo-provider
enabled: true
configs:
- addresses: ["10.20.153.10:20880"]
  side: provider
  parameters:
    disabled: true
...

**Comment by jeefgit** [comment]
> ## 动态配置里这样做？
> scope: application
> key: demo-provider
> enabled: true
> configs:
> 
> * addresses: ["10.20.153.10:20880"]
>   side: provider
>   parameters:
>   disabled: true
>   ...
是的 动态配置可以，但是最新的问题是如果有版本号和分组的时候失效

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
