### ISSUE TITLE
dubbo-admin 消费者信息不自己提交到zk

### ISSUE THREAD

**Issue by zhaoyuasd** [apache/dubbo-admin#407]
分别使用dubbo.provider和dubbo.consumer来配置生产者和消费者  服务启动后可以看到生产者  消费者调用接口成功 但是在web页面里面看不到消费者  zk里面 消费者的数据也不存在

**Comment by nzomkxia** [comment]
有没有可以复现的demo，发一下

**Comment by yuezxl** [comment]
我也碰到一样的问题 版本好为 dubbo:2.7.2
配置：
![image](https://user-images.githubusercontent.com/13274201/59560862-fd1c9800-904a-11e9-870c-a2c05e502a41.png)
![image](https://user-images.githubusercontent.com/13274201/59560914-d14de200-904b-11e9-830a-f1cda6def7c1.png)


注册中心已经有提供者,但是admin并没有消费
![image](https://user-images.githubusercontent.com/13274201/59560869-289f8280-904b-11e9-96c5-57dcc383d889.png)
admin界面也看不到
![image](https://user-images.githubusercontent.com/13274201/59560881-51277c80-904b-11e9-8282-ea7d8b274e83.png)


当我自己启动自己的消费服务后有消费者：
![image](https://user-images.githubusercontent.com/13274201/59560884-60a6c580-904b-11e9-8623-e3b86eb89810.png)

当我把dubbo admin的版本号使用0.1 tag的版本，能够服务发现，但是功能很简陋
![image](https://user-images.githubusercontent.com/13274201/59560896-a2377080-904b-11e9-8b5e-9ee97bff30fe.png)
不太清楚升级了之后版本为啥出现这样的问题

dubbo-admin的配置均为
![image](https://user-images.githubusercontent.com/13274201/59560906-c1360280-904b-11e9-8dca-3b0b157ee97d.png)

**Comment by tianyunperfect** [comment]
请问问题解决了吗？

**Comment by tianyunperfect** [comment]
我的还是有这个问题

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
