### ISSUE TITLE
MetricsService is not found

### ISSUE THREAD

**Issue by HarryPotter528** [apache/dubbo-admin#408]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project dubbo-admin-server: Compilation failure: Compilation failure: 
[ERROR] /Users/potter/Soft/incubator-dubbo-admin/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/MetrcisCollectServiceImpl.java:[22,32] 找不到符号
[ERROR]   符号:   类 MetricsService
[ERROR]   位置: 程序包 org.apache.dubbo.monitor
[ERROR] /Users/potter/Soft/incubator-dubbo-admin/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/MetrcisCollectServiceImpl.java:[26,29] 找不到符号
[ERROR]   符号:   类 MetricsService
[ERROR]   位置: 类 org.apache.dubbo.admin.service.impl.MetrcisCollectServiceImpl
[ERROR] /Users/potter/Soft/incubator-dubbo-admin/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/MetrcisCollectServiceImpl.java:[31,38] 找不到符号
[ERROR]   符号:   类 MetricsService
[ERROR]   位置: 类 org.apache.dubbo.admin.service.impl.MetrcisCollectServiceImpl
[ERROR] /Users/potter/Soft/incubator-dubbo-admin/dubbo-admin-server/src/main/java/org/apache/dubbo/admin/service/impl/MetrcisCollectServiceImpl.java:[39,9] 找不到符号
[ERROR]   符号:   类 MetricsService
[ERROR]   位置: 类 org.apache.dubbo.admin.service.impl.MetrcisCollectServiceImpl

**Comment by htynkn** [comment]
MetricsService is part of dubbo-monitor-api, maybe fail to download latest snapshot.
Could you verify snapshot version are you using in your local?

**Comment by htynkn** [comment]
Refer to https://repository.apache.org/content/repositories/snapshots/org/apache/dubbo/dubbo-monitor-api/2.7.2-SNAPSHOT/

**Comment by htynkn** [comment]
Same as https://github.com/apache/dubbo-admin/issues/397
