### ISSUE TITLE
dubbo-admin的元数据功能现在只能支持默认的dubbo么？

### ISSUE THREAD

**Issue by geekvic** [apache/dubbo-admin#410]
dubbo-admin的元数据功能现在只能支持默认的dubbo分组么，发现自定义分组后，元数据就不显示了。

**Comment by nzomkxia** [comment]
是指dubbo应用的元数据中心有自定义分组么？

**Comment by zhangviv** [comment]
指的是注册中心分组：admin.registry.group=自定义名字

**Comment by nzomkxia** [comment]
这个分组对元数据中心是生效的，只要保证和dubbo配置的一致

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
