### ISSUE TITLE
dubbo admin 服务测试 中 没有 方法列表

### ISSUE THREAD

**Issue by aworker** [apache/dubbo-admin#411]
[没有方法列表](https://github.com/aworker/picture/blob/master/dubbo/dubbo-admin%E6%9C%8D%E5%8A%A1%E6%B2%A1%E6%9C%89%E6%96%B9%E6%B3%95.png)

看dubbo admin  的demo server 服务测试中的 方法列表 是有数据的，我自己搭建的demo为什么没有数据呢？

demo的provider.xml文件核心内容如下：
` 
    <dubbo:application name="hello-world-app"  />

    
    <dubbo:registry address="zookeeper://127.0.0.1:2181" />

    
    <dubbo:protocol name="dubbo" port="20880" />

    
    <dubbo:service interface="api.DemoService" ref="demoService" />

    
    <bean id="demoService" class="provider.DemoServiceImpl" />`

包依赖：
`
<dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dubbo</artifactId>
            <version>2.6.2</version>
        </dependency>

        <dependency>
            <groupId>org.apache.curator</groupId>
            <artifactId>curator-framework</artifactId>
            <version>2.10.0</version>
        </dependency>
`

**Comment by nzomkxia** [comment]
这个功能需要dubbo 2.7及以上版本，并且配置元数据中心使用

**Comment by aworker** [comment]
好的，谢谢

**Comment by aworker** [comment]
[图片](https://github.com/aworker/picture/raw/master/dubbo/dubbo-admin%E6%9C%8D%E5%8A%A1%E6%B2%A1%E6%9C%89%E6%96%B9%E6%B3%95.png)

**Comment by lichangqingql** [comment]
怎么配置元数据中心 使用， 按照官网操作了还是不行
