### ISSUE TITLE
mvn --projects时报错

### ISSUE THREAD

**Issue by guoyuanbo** [apache/dubbo-admin#414]
![image](https://user-images.githubusercontent.com/48277401/58620561-f3c8c700-82f9-11e9-8ba3-2374d62ce8d1.png)
似乎是没有2.7.2-SNAPSHOT这个jar包导致的，但是我去官网发现最新版本也只是2.7.1的。
为什么dubbo-admin-develop直接用下一个版本了呢？即使把dubbo-admin项目的pom.xml的替换成2.7.1版本依然下载jar失败。问题没有解决，请帮助我，谢谢~

**Comment by htynkn** [comment]
2.7.2 snapshot是发布在apache snapshot的，默认的pom文件会引入该仓库。你这个应该是强制使用了aliyun maven仓库导致的。联系要么本地mvn install dubbo最新版，要么修改mvn配置，调整镜像配置

**Comment by htynkn** [comment]
https://repository.apache.org/content/repositories/snapshots/

**Comment by guoyuanbo** [comment]
非常感谢~！ @htynkn
