### ISSUE TITLE
2.6.x 是不是不支持呢

### ISSUE THREAD

**Issue by wanhuhou** [apache/dubbo-admin#415]
2.6.x 是不是不支持呢，看不到方法信息

**Comment by nzomkxia** [comment]
2.6.x支持服务治理，服务查询这些功能，但是方法信息需要2.7的元数据支持，所以看不见

**Comment by wanhuhou** [comment]
如果只用服务治理这块的话  功能使用上没有老板的admin全，是不是2.6.x不推荐是用新版的admin

**Comment by wanhuhou** [comment]
有没有钉钉开发群 关于admin的

**Comment by wanhuhou** [comment]
![image](https://user-images.githubusercontent.com/35321350/58695674-964f7b80-83c8-11e9-983f-f58d21a23425.png)

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
