### ISSUE TITLE
碰到了同样的问题， 但是修改  dubbo-admin.xml 里面的dubbo:registry 节点，配置username="super" password="superpw"  仍旧不行， 请问你使用的是什么版本的dubbo-admin

### ISSUE THREAD

**Issue by ydaming** [apache/dubbo-admin#416]
碰到了同样的问题， 但是修改  dubbo-admin.xml 里面的dubbo:registry 节点，配置username="super" password="superpw"  仍旧不行， 请问你使用的是什么版本的dubbo-admin

_Originally posted by @yrjjf in https://github.com/apache/dubbo-admin/issues/404#issuecomment-498152377_

我是download zip，下载的master分支
是不是test用户权限不够

**Comment by nzomkxia** [comment]
@ydaming 请使用`develop`分支
