### ISSUE TITLE
dubboadmin注册中心配置Eureka

### ISSUE THREAD

**Issue by Houdawei** [apache/dubbo-admin#418]
请问dubboadmin注册中心使用Eureka，怎么进行配置？

**Comment by lxhcn** [comment]
当前dubbo并不支持eureka注册
![image](https://user-images.githubusercontent.com/37830965/64513749-cee1e800-d31b-11e9-87ad-bb4c5fef72c1.png)

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
