### ISSUE TITLE
连接apollo配置中心admin.config-center配置错误

### ISSUE THREAD

**Issue by icom2014** [apache/dubbo-admin#420]
配置 成 admin.config-center=apollo://1.1.1.1:8070
报错，protal 要的portal 必须是http 或者https 开头，如果 写成  admin.config-center=apollo://http://1.1.1.1:8070  跟踪代码解析不出apollo 也不行
只有改代码 ApolloConfiguration 中
        client = ApolloOpenApiClient.newBuilder().withPortalUrl("http://"+url.getAddress()).withToken(token).build();

**Comment by icom2014** [comment]
apollo 作为配置中心集成bug 多的很，除了上面那个，还有
1、ApolloConfiguration 里的@Value  能注入进去 @Value?
2、请求apollo 的key 是 config/dubbo/dubbo.properties 也不对,就算是以前dubbo 的和 apollo 对接使用的key=dubbo..propteties 也不对啊，现在都2.7.2版本已经改成 命名空间方式。
这个应该代码写了都没测过吧

**Comment by nzomkxia** [comment]
apollo配置中心，在dubbo2.7版本迭代过程中的修改比较大，admin这里是比较早期的实现，后来一直没有完善，后面会考虑按照dubbo 2.7.2中的格式来修改，有兴趣的话可以提pr

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
