### ISSUE TITLE
mac-dubbo-admin打包编译报错

### ISSUE THREAD

**Issue by needrunning** [apache/dubbo-admin#421]
mac java-version
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)

构建

[ERROR] Failed to execute goal on project dubbo-admin-server: Could not resolve dependencies for project org.apache:dubbo-admin-server:jar:0.1: The following artifacts could not be resolved: org.apache.dubbo:dubbo:jar:2.7.2-SNAPSHOT, org.apache.dubbo:dubbo-serialization-kryo:jar:2.7.2-SNAPSHOT: Could not find artifact org.apache.dubbo:dubbo:jar:2.7.2-SNAPSHOT in apache.snapshots.https (https://repository.apache.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dubbo-admin-server
<img width="1677" alt="dubbo-admin-编译报错" src="https://user-images.githubusercontent.com/3424856/59236762-2479fc00-8c2a-11e9-80ec-8292a4a532c2.png">

**Comment by lyixi** [comment]
同样的报错，看到前面的问题说已经配置了https://repository.apache.org/content/repositories/snapshots
但是在此仓库里没有找到2.7.2-SNAPSHOT版本的jar包
![image](https://user-images.githubusercontent.com/7519760/59241524-99553200-8c3a-11e9-9632-fe262cf4f173.png)

**Comment by needrunning** [comment]
> 同样的报错，看到前面的问题说已经配置了https://repository.apache.org/content/repositories/snapshots
> 但是在此仓库里没有找到2.7.2-SNAPSHOT版本的jar包
> ![image](https://user-images.githubusercontent.com/7519760/59241524-99553200-8c3a-11e9-9632-fe262cf4f173.png)
感觉还是源码包有问题

**Comment by htynkn** [comment]
2.7.2 正式版已经发布了，所以snapshot版本移除了，这个问题稍后修复
