### ISSUE TITLE
和dubbbo2.7.2 版本一起使用并使用zk存储meata 时meta 的node 节点不统一 

### ISSUE THREAD

**Issue by icom2014** [apache/dubbo-admin#423]
dubbo 2.7.2 使用zk 作为存储metadata 的时候 ，  
存储位置是  /dubbo/metadata/x.api.DemoService/provider/xx-provider
dubbo-admin 中 取meat 信息的位置是 /dubbo/metadata/x.api.DemoService/provider/xx-provider**/service.data**
多了个 server.data

**Comment by nzomkxia** [comment]
fixed in https://github.com/apache/dubbo-admin/commit/419c7d35c29482c024123628995e3855eab72f19
