### ISSUE TITLE
ZookeeperMetaDataCollector.getNodePath方法取元数据节点路径错误

### ISSUE THREAD

**Issue by netsail** [apache/dubbo-admin#424]
由于dubbo2.7.2版本已把元数据位置改变了，ZookeeperMetaDataCollector.getNodePath方法取元数据节点路径错误。
![image](https://user-images.githubusercontent.com/5102157/59326637-be6ca200-8d19-11e9-8c86-4a3d35fc013c.png)

目前我们的解决方案：修改ZookeeperMetaDataCollector类中以下内容
    private final static String METADATA_NODE_NAME = "";//"service.data";

    private String getNodePath(MetadataIdentifier metadataIdentifier) {
        return toRootDir() + metadataIdentifier.getUniqueKey(MetadataIdentifier.KeyTypeEnum.PATH) + METADATA_NODE_NAME;
    }

**Comment by nzomkxia** [comment]
fixed in https://github.com/apache/dubbo-admin/commit/419c7d35c29482c024123628995e3855eab72f19
