### ISSUE TITLE
dubbo-admin控制台禁用应用不生效

### ISSUE THREAD

**Issue by zhaohaiyu** [apache/dubbo-admin#425]
dubbo2.7.1，在dubbo-admin上动态配置中按照官网中禁用应用：
scope: application
key: demo-provider
enabled: true
configs:
- addresses: ["10.20.153.10:20880"]
  side: provider
  parameters:
    disabled: true
不生效，消费者在请求时，请求还是会到被禁用的应用中。其中生产者有两个

**Comment by nzomkxia** [comment]
麻烦给一个官网的链接

**Comment by zhaohaiyu** [comment]
http://dubbo.apache.org/zh-cn/docs/user/demos/config-rule.html
![image](https://user-images.githubusercontent.com/51735867/59337235-ba994980-8d32-11e9-9db6-0fdade05c447.png)

**Comment by nzomkxia** [comment]
dubbo的版本是多少？

**Comment by nzomkxia** [comment]
试一下升级到dubbo 2.7.2

**Comment by zhaohaiyu** [comment]
试了，2.7.2也不行；而且dubbo2.7.2元数据在zookeeper保存的路径和2.7.1不一样，dubbo-admin提示服务没有元数据。
示例：2.7.1的元数据保存路径：/dubbo/metadata/com.hshbic.ai.dubbo.service.dot.DotService/provider/dot-adapter/service.data，
而2.7.2的路径没有service.data

**Comment by nzomkxia** [comment]
> 试了，2.7.2也不行；而且dubbo2.7.2元数据在zookeeper保存的路径和2.7.1不一样，dubbo-admin提示服务没有元数据。
> 示例：2.7.1的元数据保存路径：/dubbo/metadata/com.hshbic.ai.dubbo.service.dot.DotService/provider/dot-adapter/service.data，
> 而2.7.2的路径没有service.data

dubbo admin已经做了更新 请拉取最新的develop分支解决2.7.2元数据路径不一样的问题
我这里试了下2.7.2是可以禁用的，你把zk里面对应的规则贴一下

**Comment by zhaohaiyu** [comment]
> dubbo admin已经做了更新 请拉取最新的develop分支解决2.7.2元数据路径不一样的问题
> 我这里试了下2.7.2是可以禁用的，你把zk里面对应的规则贴一下

我用2.7.2试了，还是不行。在控制台配置时的规则：
![image](https://user-images.githubusercontent.com/51735867/59492754-34107380-8ebc-11e9-92ce-69d3c72ce4c5.png)
保存到zk中是这样的：
![image](https://user-images.githubusercontent.com/51735867/59492844-67530280-8ebc-11e9-85d1-f820357585c9.png)
我的两个服务提供者信息：
![image](https://user-images.githubusercontent.com/51735867/59492966-b00abb80-8ebc-11e9-8866-792d87bb0f98.png)

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
