### ISSUE TITLE
dubbo-admin-ui编译失败，报src\components\ServiceSearch.vue:305:104错

### ISSUE THREAD

**Issue by haien** [apache/dubbo-admin#427]
如图

![QQ截图20190613104337](https://user-images.githubusercontent.com/16283827/59400147-0d254500-8dc9-11e9-88b9-5618c82d7485.jpg)

**Comment by aworker** [comment]
这个是因为 写的js 不符合 eslint语法，将 ServiceSearch.Vue 第305行后面的分号去掉就可以了。

**Comment by haien** [comment]
谢谢
