### ISSUE TITLE
元数据中心路径写错了，导致报错

### ISSUE THREAD

**Issue by independenter** [apache/dubbo-admin#428]
![image](https://user-images.githubusercontent.com/32162481/59518136-9f2b6b80-8ef7-11e9-8ba9-66c9ed9ddca3.png)
org.apache.dubbo.admin.registry.metadata.impl.ZookeeperMetaDataCollector#getNodePath
路径应该是/dubbo/metadata/XXX.Service/provider/BSP-base-provider/service.data

**Comment by independenter** [comment]
修改后正常
![image](https://user-images.githubusercontent.com/32162481/59518250-e0bc1680-8ef7-11e9-87e2-eaccaa460acf.png)

**Comment by nevin9939** [comment]
我看了代码，dubbo2.7.1的元数据空间路径是带service.data   升级到dubbo2.7.2把这层路径去掉了

**Comment by independenter** [comment]
其实去掉了好，少一层路径，效率更高点，我用的dubbo2.7.1，所以dubbo-admin这里要改了才可以正常

**Comment by hudandan** [comment]
哈哈 踩到一样的问题

**Comment by DongyangZhu** [comment]
2.7.3 该咋改？o(╥﹏╥)o  地址这样的：/dubbo/metadata/com.demo.demoapi.service.providers.DemoService/provider/providers/service.data
![image](https://user-images.githubusercontent.com/16877322/62282298-dfcc4d80-b481-11e9-8ff1-2ee7c6709b19.png)

**Comment by independenter** [comment]
用zookeeper客户端，或者其他可视化工具看下dubbo在zookeeper内保存的路径，和这个对应上就行了

**Comment by DongyangZhu** [comment]
> 用动物园管理员客户端，或者其他可视化工具看下达博在动物园管理员内保存的路径，和这个对应上就行了

新下个Admin 就好了，发现Admin新版本好像有bug，老是有缓存。

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
