### ISSUE TITLE
注册中心有正常服务注册发现，但是dubbo-admin上不显示相关信息

### ISSUE THREAD

**Issue by yuezxl** [apache/dubbo-admin#430]
我也碰到一样的问题 版本好为 dubbo:2.7.2
配置：

![image](https://user-images.githubusercontent.com/13274201/59560962-a87a1c80-904c-11e9-86a0-d22f412e2ef0.png)

![image](https://user-images.githubusercontent.com/13274201/59560862-fd1c9800-904a-11e9-870c-a2c05e502a41.png)

注册中心已经有提供者,但是admin并没有消费
![image](https://user-images.githubusercontent.com/13274201/59560869-289f8280-904b-11e9-96c5-57dcc383d889.png)
admin界面也看不到
![image](https://user-images.githubusercontent.com/13274201/59560881-51277c80-904b-11e9-8282-ea7d8b274e83.png)

当我自己启动自己的消费服务后有消费者：
![image](https://user-images.githubusercontent.com/13274201/59560884-60a6c580-904b-11e9-8623-e3b86eb89810.png)

当我把dubbo admin的版本号使用0.1 tag的版本，能够服务发现，但是功能很简陋
![image](https://user-images.githubusercontent.com/13274201/59560896-a2377080-904b-11e9-8b5e-9ee97bff30fe.png)
不太清楚升级了之后版本为啥出现这样的问题

dubbo-admin的配置均为
![image](https://user-images.githubusercontent.com/13274201/59560906-c1360280-904b-11e9-8dca-3b0b157ee97d.png)

_Originally posted by @yuezxl in https://github.com/apache/dubbo-admin/issues/407#issuecomment-502428575_

**Comment by mumushigeluobo** [comment]
我也遇到过

**Comment by zhaohaiyu** [comment]
dubbo使用2.7.2，dubbo-admin拉一个最新的，元数据路径不一致的问题已经解决

**Comment by yuezxl** [comment]
> 我也碰到一样的问题 版本好为 dubbo:2.7.2
> 配置：
> 
> ![image](https://user-images.githubusercontent.com/13274201/59560962-a87a1c80-904c-11e9-86a0-d22f412e2ef0.png)
> 
> ![image](https://user-images.githubusercontent.com/13274201/59560862-fd1c9800-904a-11e9-870c-a2c05e502a41.png)
> 
> 注册中心已经有提供者,但是admin并没有消费
> ![image](https://user-images.githubusercontent.com/13274201/59560869-289f8280-904b-11e9-96c5-57dcc383d889.png)
> admin界面也看不到
> ![image](https://user-images.githubusercontent.com/13274201/59560881-51277c80-904b-11e9-8282-ea7d8b274e83.png)
> 
> 当我自己启动自己的消费服务后有消费者：
> ![image](https://user-images.githubusercontent.com/13274201/59560884-60a6c580-904b-11e9-8623-e3b86eb89810.png)
> 
> 当我把dubbo admin的版本号使用0.1 tag的版本，能够服务发现，但是功能很简陋
> ![image](https://user-images.githubusercontent.com/13274201/59560896-a2377080-904b-11e9-8b5e-9ee97bff30fe.png)
> 不太清楚升级了之后版本为啥出现这样的问题
> 
> dubbo-admin的配置均为
> ![image](https://user-images.githubusercontent.com/13274201/59560906-c1360280-904b-11e9-8dca-3b0b157ee97d.png)
> 
> _Originally posted by @yuezxl in [#407 (comment)](https://github.com/apache/dubbo-admin/issues/407#issuecomment-502428575)_

我debug了一下，返现服务端是返回的没问题，js报错不显示了
![image](https://user-images.githubusercontent.com/13274201/59620622-def48c00-915f-11e9-8e34-5870a8af0c48.png)

![image](https://user-images.githubusercontent.com/13274201/59620333-24fd2000-915f-11e9-80be-b91dc251cd7e.png)

**Comment by nzomkxia** [comment]
你的代码是`develop`分支最新的么？现在的服务查询默认是带分页的，看到你的截图上并没有：   
![image](https://user-images.githubusercontent.com/1183397/59739895-e9ff0780-9298-11e9-8529-a4ccd1ce2a94.png)

**Comment by yuezxl** [comment]
> 你的代码是`develop`分支最新的么？现在的服务查询默认是带分页的，看到你的截图上并没有：
> ![image](https://user-images.githubusercontent.com/1183397/59739895-e9ff0780-9298-11e9-8529-a4ccd1ce2a94.png)

是最新分之，不过我的node modules好像有问题，我把node的删了，重新安装好像就好了。
