### ISSUE TITLE
条件路由设置应用维度不生效

### ISSUE THREAD

**Issue by hudandan** [apache/dubbo-admin#433]
条件路由设置，应用维度的条件路由设置不生效。但是服务维度的设置是可以的

**Comment by nzomkxia** [comment]
dubbo版本是多少？提供一个demo

**Comment by hudandan** [comment]
dubbo版本最新的2.7.3，后续截图给详细说明

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
