### ISSUE TITLE
配置中心菜单功能使用bug

### ISSUE THREAD

**Issue by 799983050** [apache/dubbo-admin#438]
![图片](https://user-images.githubusercontent.com/45658355/60011292-0f7e7d80-96ac-11e9-9a58-bcfcd456f7b8.png)
我使用了几分钟，就出现好多问题，请问没有专门的测试人员吗？基本功能为什么还这么多bug。
1、搜索*或者空，不能查询出所有的记录。最后也没发现怎么看所有的记录
2、修改页面，修改应用名称点击保存后，变成新增一条记录。
3、dubbo-admin现在无法兼容dubbo2.7.2版本

**Comment by nzomkxia** [comment]
1. 配置没有搜索全局的功能
2. 提供一个demo
3. 目前`develop`分支适配了dubbo 2.7.2的元数据版本
