### ISSUE TITLE
BEGIN_OBJECT but was STRING at line 1 column 1

### ISSUE THREAD

**Issue by mingyang66** [apache/dubbo-admin#439]
查看服务信息报：
Message:java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by aworker** [comment]
@mingyang66  能把admin的配置信息发下吗？ 还有具体的ui层面请求

**Comment by mingyang66** [comment]
是我在服务提供者这边的配置文件中加入以下配置后出现的：
##元数据配置中心地址
dubbo.metadata-report.address=${dubbo.registry.protocol}://127.0.0.1:${dubbo.registry.port}

**Comment by mingyang66** [comment]
以下是admin的配置：
# centers in dubbo2.7
admin.registry.address=zookeeper://127.0.0.1:2181
admin.config-center=zookeeper://127.0.0.1:2181
admin.metadata-report.address=zookeeper://127.0.0.1:2181



admin.registry.group=dubbo
admin.apollo.token=e16e5cd903fd0c97a116c873b448544b9d086de9
admin.apollo.appId=test
admin.apollo.env=dev
admin.apollo.cluster=default
admin.apollo.namespace=dubbo

**Comment by mingyang66** [comment]
Request URL: http://localhost:9000/api/dev/service/com.dubbo.provider.service.DemoService:2.7.1
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:9000
Referrer Policy: no-referrer-when-downgrade
{"success":false,"message":"System Error, please try again later! Message:java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $"}

**Comment by nzomkxia** [comment]
dubbo服务对于`${dubbo.registry.protocol}`和`${dubbo.registry.port}`的解析正确么？有没有连到元数据中心

**Comment by ettingshausen** [comment]
遇到了同样的问题，问题出现在 `ServiceController` 中的 99 行:
```java
FullServiceDefinition serviceDefinition = gson.fromJson(metadata, FullServiceDefinition.class);
```
不知道为什么 `metadata` 是个IP地址
![Snipaste_2019-07-05_20-04-31](https://user-images.githubusercontent.com/9806325/60721354-3f593b00-9f60-11e9-802e-fd0eac4743f6.png)

**Comment by ettingshausen** [comment]
可以确定是版本问题，升级至2.7.2就好了  
https://github.com/apache/dubbo-admin/commit/419c7d35c29482c024123628995e3855eab72f19#commitcomment-34200155

**Comment by lyixi** [comment]
api/dev/service访问此接口报错：Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

**Comment by nzomkxia** [comment]
由于2.7.1和之后版本在原数据格式上没有保持兼容，请升级到dubbo 2.7.2及以后版本
