### ISSUE TITLE
不使用注册中心的应用怎么配置 admin？

### ISSUE THREAD

**Issue by xiangwang189** [apache/dubbo-admin#444]
服务端是个单机，客户端通过设置 url 直连访问的，没有使用 zookeeper，要使用 dubbo-admin 怎么配置呢？

**Comment by aworker** [comment]
这种情况应该是不支持使用admin的

**Comment by nzomkxia** [comment]
这种情况在admin上看不到服务，但是配置好配置，元数据中心以后，依然可以做服务治理和服务测试
