### ISSUE TITLE
没有账号登录吗

### ISSUE THREAD

**Issue by phoenixying** [apache/dubbo-admin#455]
这个新版的dubbo admin 不需要登录吗？可以设置成 账号密码登录才能看到服务监控吗？

**Comment by zhiyongwang** [comment]
同问

**Comment by demonshir** [comment]
这个新版的dubbo admin 需要登录吗？可以设置成 不需要账号密码登录就能看到服务监控吗？

**Comment by kexianjun** [comment]
配置文件里面默认的用户名密码 root/root,如果不想用登陆功能加上如下配置即可
> admin.check.authority=false
