### ISSUE TITLE
System Error, please try again later! Message:java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

### ISSUE THREAD

**Issue by zpLiuHH** [apache/dubbo-admin#456]
dubbo version:2.7.1
zookeeper version:3.5.5
启动dubbo-admin和dubbo-demo服务后在服务查询页面可以查询到dubbo-demo提供的服务，点击详情后在页面底部会出现以下错误：System Error, please try again later! Message:java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $

详细页面只有基础信息，服务信息无内容。
元数据相关配置如下：
dubbo.configcenter="zookeeper://127.0.0.1:2181"
dubbo.metadata-report.address=zookeeper://127.0.0.1:2181
显示无元数据

**Comment by aworker** [comment]
把dubbo.configcenter 后面的 双引号去掉

**Comment by zpLiuHH** [comment]
@aworker 我使用的是xml配置形式，另外，我用properties配置文件形式测试过了，加上双引号和去掉双引号效果一样，无法解决问题。

**Comment by zpLiuHH** [comment]
重新把最新的代码clone到本地，然后在dubbo-demo-xml和dubbo-demo-annotation的pom文件中加入了
`<dependency> <groupId>org.apache.dubbo</groupId> <artifactId>dubbo-metadata-report-zookeeper</artifactId> <version>${project.parent.version}</version> </dependency>`

在dubbo-provider.xml和dubbo-provider.properties中分别加入了如下配置：dubbo.configcenter=zookeeper://127.0.0.1:2181
dubbo.metadata-report.address=zookeeper://127.0.0.1:2181
然后成功运行，并在dubbo-admin的管理界面及服务的详细页面元数据部分能正常显示。
总结来说应该还是配置和pom的原因。

**Comment by charlieli2005** [comment]
我使用的是 spring boot 2, dubbo 相关的依赖都是2.7.3 以上， 上述问题一样存在。。。


	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>



		
		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo</artifactId>
			<version>${dubbo.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-context</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.apache.dubbo</groupId>
			<artifactId>dubbo-spring-boot-starter</artifactId>
			<version>${dubbo.version}</version>
		</dependency>






		<dependency>
			<groupId>org.apache.curator</groupId>
			<artifactId>curator-framework</artifactId>
			<version>${curator-framework.version}</version>
		</dependency>

		
		<dependency>
			<groupId>org.apache.curator</groupId>
			<artifactId>curator-recipes</artifactId>
			<version>${curator-framework.version}</version>
		</dependency>
		
		<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-metadata-report-zookeeper</artifactId>
 <version>${dubbo.version}</version>
</dependency>
