### ISSUE TITLE
dubbo admin找不到元数据原因（针对dubbo2.7.2版本）

### ISSUE THREAD

**Issue by 18702524676** [apache/dubbo-admin#457]
>dubbo2.7.2注册到zk上的metadate（原）路径发生变化，dubbo admin源码中获取的路径还上2.7.2之前的版本的路径，所以找不到元数据，解决这个问题只需要修改下拼接路径的方法即可
#### 进入ZookeeperMetaDataCollector.getNodePath()函数
修改为：
```
private String getNodePath(MetadataIdentifier metadataIdentifier) {
        return toRootDir() + metadataIdentifier.getUniqueKey(MetadataIdentifier.KeyTypeEnum.PATH);
       // + Constants.PATH_SEPARATOR + METADATA_NODE_NAME; 2.7.2元数据路径已经更换
    }
```

**Comment by ArtificialIdoit** [comment]
我的2.7.2是这样的
```
private String getNodePath(MetadataIdentifier metadataIdentifier) {
        return toRootDir() + metadataIdentifier.getUniqueKey(MetadataIdentifier.KeyTypeEnum.PATH);
    }
```
但还是有问题

**Comment by 18702524676** [comment]
相关的配置有没有配好，你开一个打个断点在这里 看下路径对不对的上zk上的元数据路径

**Comment by zhanngyun** [comment]
private String getNodePath(MetadataIdentifier metadataIdentifier) {
        return toRootDir() + metadataIdentifier.getUniqueKey(MetadataIdentifier.KeyTypeEnum.PATH) + "/service.data";
    }

**Comment by zhanngyun** [comment]
private String getNodePath(MetadataIdentifier metadataIdentifier) {
        return toRootDir() + metadataIdentifier.getUniqueKey(MetadataIdentifier.KeyTypeEnum.PATH) + "/service.data";
    }
我在后面加了一个 "/service.data"就好了，不知道我的配置有问题还是一个bug

**Comment by nzomkxia** [comment]
当前`develop`分支已经修复这个问题了，适配了最新版本的元数据路径
