### ISSUE TITLE
一个服务创建多个条件路由

### ISSUE THREAD

**Issue by sunnyczj** [apache/dubbo-admin#460]
一个服务创建多个条件路由后，页面只能查出最后一条，但其实 zookeeper中是有多个路由记录的

**Comment by nzomkxia** [comment]
哪个版本的dubbo？如果是2.7的话 应该只会有一条

**Comment by sunnyczj** [comment]
2.7.2  dubbo ， 0.2.0  dubbo-admin

**Comment by nzomkxia** [comment]
@sunnyczj 请提供一个demo，我这边试了下只有一条
