### ISSUE TITLE
dubbo 2.7.2版本无法找到元数据，统计功能无法使用

### ISSUE THREAD

**Issue by ArtificialIdoit** [apache/dubbo-admin#463]
我是用api方式实现的，另外元数据会不会影响统计功能？我发现统计功能也无法使用。

**Comment by yuezxl** [comment]
如果你是使用zk，我看2.7.2的元数据路径应该是在/dubbo/metadata/com.*.*Service/1.0.0/${group}/provider/${application}/service.data 下。dubbo admin 获取元数据的方法在 ZookeeperMetaDataCollector中，是用的path并没有 /service.data，可以自己加上 /service.data获取元数据试试。
![image](https://user-images.githubusercontent.com/13274201/62093074-6d554500-b2aa-11e9-9964-ade95bcb903a.png)

**Comment by DongyangZhu** [comment]
![image](https://user-images.githubusercontent.com/16877322/62279914-8f52f100-b47d-11e9-86be-1b0b8d0dd3b4.png)
![Uploading image.png…]()
有呀 看这是加上了

**Comment by DongyangZhu** [comment]
> 如果你是使用zk，我看2.7.2的元数据路径应该是在/dubbo/metadata/com.*.*Service/1.0.0/${group}/provider/${application}/service.data 下。dubbo admin 获取元数据的方法在 ZookeeperMetaDataCollector中，是用的path并没有 /service.data，可以自己加上 /service.data获取元数据试试。
> 
![image](https://user-images.githubusercontent.com/16877322/62280076-d0e39c00-b47d-11e9-996b-b907a767b4e4.png)
看官方的代码里加上了呀

**Comment by shenhuqiji1991** [comment]
感谢楼上老哥,官方坑人

**Comment by nzomkxia** [comment]
dubbo 2.7.3中的元数据路径有变化，目前dubbo admin的代码是适配dubbo 2.7.3，没有作之前版本的兼容
