### ISSUE TITLE
dubbo-admin什么时候会支持nacos?

### ISSUE THREAD

**Issue by zgqq** [apache/dubbo-admin#464]
nacos能做注册中心，和配置管理很方便，现在又得换回zookeeper...

**Comment by CoderPoet** [comment]
> nacos能做注册中心，和配置管理很方便，现在又得换回zookeeper...

凶dei，多注册中心将就一下吧

**Comment by kexianjun** [comment]
registry center has already been supported, and metadata center is supported in #465

**Comment by chenquanzhen** [comment]
> registry center has already been supported, and metadata center is supported in #465

但dubbo amin 动态配置功能不支持啊

**Comment by DaveRoey** [comment]
how to use it?

**Comment by kexianjun** [comment]
> > registry center has already been supported, and metadata center is supported in #465
> 
> 但dubbo amin 动态配置功能不支持啊

refer to #494

**Comment by kexianjun** [comment]
> how to use it?

for metadata-report, add the following config application.properties file in your dubbo-admin 

> admin.metadata-report.address=nacos://10.0.10.44:8848

the registry and dynamic config is the same

**Comment by kexianjun** [comment]
nacos has been supported
