### ISSUE TITLE
已经停止的服务接口还在admin中

### ISSUE THREAD

**Issue by Skqing** [apache/dubbo-admin#469]
![image](https://user-images.githubusercontent.com/1713001/61365778-e1f7af00-a8ba-11e9-8520-ad59d47693c3.png)
请问改如何解决？

**Comment by DongyangZhu** [comment]
正常情况是不存在的，可能是服务确实没停止

**Comment by colove** [comment]
If the version of dubbo that you are using is 2.7.1, it will appear this problem , In version of dubbo-2.7.1, it has a bug that causing the provider repeat registration
