### ISSUE TITLE
项目启动日志报错

### ISSUE THREAD

**Issue by jimiyi** [apache/dubbo-admin#471]
虽然系统resources路径下有logback-spring.xml文件，但是启动的时候还是报了
log4j:WARN No appenders could be found for logger (org.apache.dubbo.common.logger.LoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
且看不到启动日志

**Comment by htynkn** [comment]
Currently CI passed. Please refer to:
https://github.com/apache/dubbo-admin/blob/develop/.github/workflows/ci.yml
https://github.com/apache/dubbo-admin/blob/develop/docker/0.2.0/Dockerfile

if still not work, try start via maven command instead of main class directly
