### ISSUE TITLE
无元数据信息，请升级至Dubbo2.7及以上版本，或者查看application.properties中关于config center的配置

### ISSUE THREAD

**Issue by itlihuaxin** [apache/dubbo-admin#476]
在服务查询页面一直看不了元数据
incubator-dubbo-admin/dubbo-admin-server/src/main/resources/application.properties的配置是
admin.config-center=zookeeper://192.168.99.107:2181

页面上全局配置是
dubbo.registry.address=zookeeper://192.168.99.107:2181
dubbo.metadata-report.address=zookeeper://192.168.99.107:2181

服务提供者的配置是
dubbo.config-center.address=zookeeper://192.168.99.107:2181

**Comment by itlihuaxin** [comment]
版本是dubbo 2.7.3

**Comment by huangjinvv** [comment]
同样不行

**Comment by huangjinvv** [comment]
@itlihuaxin  我看了admin的代码，目前应该只支持dubbo 2.7.0版本，dubbo 2.7.3版本metadata存储的key生成规则已更新，admin的代码还是老规则，所以无法获取到元数据

**Comment by nzomkxia** [comment]
目前的`develop`版本已经适配了dubbo 2.7.3的生成规则，请试一下

**Comment by meteorice** [comment]
我看老规则获取的地址是 /dubbo/metadata/com.example.demo.service.ICardDictService/1.0/demo-provider/provider/demo-group/service.data
2.7.3 没有service.data 目录元数据直接在demo-group写入。

**Comment by pengyonglei** [comment]
现在 2.7.5 版本又不行了 ? 是不是还需要做一下适配呢?

**Comment by DevinXin** [comment]
2.7.7 版本也不行

**Comment by RobertoHuang** [comment]
2.7.8 版本好像也不行
