### ISSUE TITLE
目前集成nacos，dubbo admin动态配置的功能不生效

### ISSUE THREAD

**Issue by chenquanzhen** [apache/dubbo-admin#483]
原数据中心，配置中心改为nacos, 测试功能可用，但动态配置功能能修改，但实际不生效

**Comment by DaveRoey** [comment]
请问怎么集成的，我看源码没有nacos的配置中心代码，元数据中心倒是有。

**Comment by chenquanzhen** [comment]
> 请问怎么集成的，我看源码没有nacos的配置中心代码，元数据中心倒是有。

加入dubbo-registry-nacos 依赖就可以

**Comment by DaveRoey** [comment]
我加入了dubbo-registry-nacos依赖，修改配置文件为admin.config-center=nacos://127.0.0.1:8848，却发生了异常 No such extension org.apache.dubbo.admin.registry.config.GovernanceConfiguration by name nacos。

**Comment by chenquanzhen** [comment]
> 我加入了dubbo-registry-nacos依赖，修改配置文件为admin.config-center=nacos://127.0.0.1:8848，却发生了异常 No such extension org.apache.dubbo.admin.registry.config.GovernanceConfiguration by name nacos。

META-INF/dubbo/internal/org.apache.dubbo.admin.registry.config.GovernanceConfiguration把nacos配上

**Comment by goodTerry** [comment]
nacos=org.apache.dubbo.admin.registry.config.impl.NacosConfiguration
META-INF/dubbo/internal/org.apache.dubbo.admin.registry.config.GovernanceConfiguration这个是加上这个配置吗

**Comment by chenquanzhen** [comment]
> nacos=org.apache.dubbo.admin.registry.config.impl.NacosConfiguration
> META-INF/dubbo/internal/org.apache.dubbo.admin.registry.config.GovernanceConfiguration这个是加上这个配置吗

是的，NacosConfiguration要实现下GovernanceConfiguration接口

**Comment by goodTerry** [comment]
> > nacos=org.apache.dubbo.admin.registry.config.impl.NacosConfiguration
> > META-INF/dubbo/internal/org.apache.dubbo.admin.registry.config.GovernanceConfiguration这个是加上这个配置吗
> 
> 是的，NacosConfiguration要实现下GovernanceConfiguration接口

如何实现呢？有没有源码可以分享一下

**Comment by chenquanzhen** [comment]
> > > nacos=org.apache.dubbo.admin.registry.config.impl.NacosConfiguration
> > > META-INF/dubbo/internal/org.apache.dubbo.admin.registry.config.GovernanceConfiguration这个是加上这个配置吗
> > 
> > 
> > 是的，NacosConfiguration要实现下GovernanceConfiguration接口
> 
> 如何实现呢？有没有源码可以分享一下

参考nacos元数据中心的实现

**Comment by kexianjun** [comment]
refer to #494

**Comment by kexianjun** [comment]
nacos has been supported

**Comment by hepyu** [comment]
> nacos has been supported

dubbo-admin的docker镜像应该更新了。
