### ISSUE TITLE
统计页面显示Metrics会在后续版本中发布，敬请期待

### ISSUE THREAD

**Issue by SparkandScala** [apache/dubbo-admin#485]
version ： dubbo-admin-0.2.0

dubbo-version：2.7.3

我在网上看到一个demo，2.7.2的版本dubbo可以看到 统计页面

**Comment by nzomkxia** [comment]
嗯 2.7.2版本可以看到，请参考这个sample来进行配置：https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-metrics
