### ISSUE TITLE
Admin-ui无法查看服务的方法列表？

### ISSUE THREAD

**Issue by tanrui988** [apache/dubbo-admin#487]
![微信截图_20190822111841](https://user-images.githubusercontent.com/52195390/63483326-9befc580-c4ce-11e9-9871-3cc6382633f3.png)

服务查询里可以查询出所有注册的服务列表。但是想通过方法列表死活找不到。请指导下。

**Comment by netyjq** [comment]
@tanrui988 请问你是怎么解决的
