### ISSUE TITLE
新版的admin—0.2.0.relese页面权重查询

### ISSUE THREAD

**Issue by sissi-feng** [apache/dubbo-admin#489]
设置权重时，由于无法同时设置服务名和应用名，如图：
![image](https://user-images.githubusercontent.com/13548936/63584471-9928c980-c5cf-11e9-98b5-a91e4a3c32dd.png)

所以查询时，会出现如图所示：
![image](https://user-images.githubusercontent.com/13548936/63584587-d8efb100-c5cf-11e9-80ad-82e423149f9f.png)
点击右侧按钮，无任何效果，Vue代码报错。

**Comment by nzomkxia** [comment]
dubbo 2.7开始，支持应用维度的规则，因此在新建，查询的时候，提供了应用和服务两个维度，但是不能同时，否则无法确定该条规则的作用范围到底是应用还是服务
