### ISSUE TITLE
Error finding remote resources manifests

### ISSUE THREAD

**Issue by 00jiajia** [apache/dubbo-admin#490]
一个admin 搞地如此复杂，就执行一个mvn clean package，一直报 Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (process-resource-bundles) on project dubbo-admin: Error finding remote resources manifests: C:\Users\jia\Desktop\navicat\dubbo-admin-develop\target\maven-shared-archive-resources\META-INF\NOTICE (系统找不到指定的路径。) -> [Help 1]
对于一个刚入门的人，死活找不到原因，查了好几天，老哥，要么你文档写清楚一点，要么你的包都弄得齐全一点，还有就是pom文件也不能修改。就随便写个mvn clean package 挖坑，以后你这控件如何推广

**Comment by nzomkxia** [comment]
dubbo admin 没有依赖`maven-remote-resources-plugin`这个插件，`mvn clean package`不是随便写的，是因为用这个命令可以运行起来

**Comment by ye0401** [comment]
> 一个admin 搞地如此复杂，就执行一个mvn clean package，一直报 Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (process-resource-bundles) on project dubbo-admin: Error finding remote resources manifests: C:\Users\jia\Desktop\navicat\dubbo-admin-develop\target\maven-shared-archive-resources\META-INF\NOTICE (系统找不到指定的路径。) -> [Help 1] 对于一个刚入门的人，死活找不到原因，查了好几天，老哥，要么你文档写清楚一点，要么你的包都弄得齐全一点，还有就是pom文件也不能修改。就随便写个mvn clean package 挖坑，以后你这控件如何推广

老哥这个问题咋解决的

**Comment by bigajiu** [comment]
> > 一个admin 搞地如此复杂，就执行一个mvn clean package，一直报 Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (process-resource-bundles) on project dubbo-admin: Error finding remote resources manifests: C:\Users\jia\Desktop\navicat\dubbo-admin-develop\target\maven-shared-archive-resources\META-INF\NOTICE (系统找不到指定的路径。) -> [Help 1] 对于一个刚入门的人，死活找不到原因，查了好几天，老哥，要么你文档写清楚一点，要么你的包都弄得齐全一点，还有就是pom文件也不能修改。就随便写个mvn clean package 挖坑，以后你这控件如何推广
> 
> 老哥这个问题咋解决的

我这边解决了，用 sudo 加上 mvn clean package
