### ISSUE TITLE
dubbo-admin0.2.0release版本UI无法启动

### ISSUE THREAD

**Issue by sissi-feng** [apache/dubbo-admin#491]
使用admin0.2.0release版本启动前端界面，使用npm install 和npm run dev 没有问题，但是访问localhost:8081时，出现如图问题
![image](https://user-images.githubusercontent.com/13548936/63677996-cfa95300-c820-11e9-9b8a-5bbc4eb01810.png)

将版本切换成develop版本后，启动正常。

目前怀疑是两个分支，编译UI界面的方式不一样导致

**Comment by nzomkxia** [comment]
`0.2.0-release`分支当时为了符合apache的发布规则，去掉了很多前端组件，已经删除了，请使用`develop`分支
