### ISSUE TITLE
统计模块无法使用

### ISSUE THREAD

**Issue by Armstjoh** [apache/dubbo-admin#497]
一、元数据配好了redis集群，但是在元数据的json中parameters中无metrics.port数据。
在dubbo-admin中对应的源码configMap.put(parameters.get(Constants.METRICS_PORT), parameters.get(Constants.METRICS_PROTOCOL));

二、在项目中注册中心配置了zookeeper中simplified: true后，dubbo-admin服务测试才能使用。

**Comment by Armstjoh** [comment]
在项目application.yml中没有  dubbo.metrics.port: 20880的属性映射。

**Comment by Armstjoh** [comment]
找到问题了，dubbo2.7.3还没有修改这个问题，在git分支#4505已经修改好了，希望发布2.7.4时能用上，谢谢。

**Comment by dmtd78** [comment]
伙计，你的问题搞定了吗？

**Comment by Armstjoh** [comment]
> 伙计，你的问题搞定了吗？

https://github.com/apache/dubbo-admin/issues/507
