### ISSUE TITLE
nacos作为注册中心时，条件路由配置不起作用

### ISSUE THREAD

**Issue by manbab** [apache/dubbo-admin#522]
dubbo2.7版本，使用nacos作为注册和配置中心
nacos.address = 192.168.0.204:8868
nacos.dataId = EsMobileServerLauncher
nacos.namespace = 18439051-b8bb-471c-950e-49adbdffb455
dubbo.registry.address = nacos://192.168.0.204:8868?namespace=18439051-b8bb-471c-950e-49adbdffb455
条件路由设置如下
conditions:
- => host != 192.168.0.206
enabled: true
force: true
key: com.everstar.mobile.service.INetEventService:1.0.0
priority: 0
runtime: true
scope: service

最后发现还是再206上执行了，这条规则没有产生效果
请问如何配置才能生效

**Comment by manbab** [comment]
dubbo-admin 配置
server.port=8086
admin.registry.address=nacos://192.168.0.204:8868?namespace=18439051-b8bb-471c-950e-49adbdffb455
admin.config-center=nacos://192.168.0.204:8868?namespace=18439051-b8bb-471c-950e-49adbdffb455
admin.metadata-report.address=nacos://192.168.0.204:8868?namespace=18439051-b8bb-471c-950e-49adbdffb455

**Comment by kexianjun** [comment]
I'll check this later

**Comment by manbab** [comment]
还需要别的说明么？？？？

**Comment by manbab** [comment]
![image](https://user-images.githubusercontent.com/3623460/66556991-c4697700-eb83-11e9-97ff-7606c1adcf21.png)
这个是nacos服务列表中多出了一条routers记录
![image](https://user-images.githubusercontent.com/3623460/66557183-0b576c80-eb84-11e9-9a7a-8d69fd23174d.png)
这个是详细信息

**Comment by manbab** [comment]
routers:::1.0.0:   这个地方出现了问题，每次设置，都会覆盖当条记录，应该是dubbo-admin在用nacos时创建routers有bug

**Comment by kexianjun** [comment]
nacos 动态配置中心的实现有bug，稍后我看看怎么修掉吧

**Comment by manbab** [comment]
好的，tks

**Comment by kexianjun** [comment]
@manbab,我提交了一个 pr #525 ,条件路由规则下发以及其他动态配置下发都可以了，麻烦看一下是否解决了你的问题

**Comment by manbab** [comment]
我做下测试

**Comment by manbab** [comment]
做了个测试，规则不变，206上服务依然被调用了
conditions:
- => host != 192.168.0.206
enabled: true
force: true
key: com.everstar.mobile.service.INetEventService:1.0.0
priority: 0
runtime: false
scope: service

**Comment by manbab** [comment]
在增加路由时，服务列表里的routers:::1.0.0:对应的元数据也被覆盖了

**Comment by manbab** [comment]
创建和修改条件路由时控制台回报错
![image](https://user-images.githubusercontent.com/3623460/66700167-54442800-ed20-11e9-90b3-35f638127ccd.png)

**Comment by kexianjun** [comment]
> 在增加路由时，服务列表里的routers:::1.0.0:对应的元数据也被覆盖了

这个被覆盖是应该是拼接的时候漏掉了服务名导致的，已经修了

**Comment by kexianjun** [comment]
> 做了个测试，规则不变，206上服务依然被调用了
> conditions:
> 
> * => host != 192.168.0.206
>   enabled: true
>   force: true
>   key: com.everstar.mobile.service.INetEventService:1.0.0
>   priority: 0
>   runtime: false
>   scope: service

不生效的原因应该是 nacos 作为注册中心的时候，消费者端没有订阅 routers:xxx 节点导致的；2.7 以上的版本建议使用动态配置中心来做服务治理

**Comment by kexianjun** [comment]
> 创建和修改条件路由时控制台回报错
> ![image](https://user-images.githubusercontent.com/3623460/66700167-54442800-ed20-11e9-90b3-35f638127ccd.png)

这个控制台页面报错我本地没有复现

**Comment by manbab** [comment]
我在做下测试看看

**Comment by manbab** [comment]
routers:com.everstar.mobile.service.INetEventService:1.0.0:  
这个地方正常了，
调用时206还是会执行
我的配置文件如下

> nacos.address = 192.168.1.199:8848
> nacos.dataId = dubbo-EsMobileClientLauncher-cousumer
> nacos.namespace = fd4c2b5d-3649-4558-b85f-50b2f0eb6c4a
> dubbo.registry.address = nacos://192.168.1.199:8848?namespace=fd4c2b5d-3649-4558-b85f-50b2f0eb6c4a



我的启动注解如下
```
@SpringBootApplication
@Configuration
//@EnableCaching
//@EnableSwagger2
@EnableDubbo(scanBasePackages = "com") 
@EnableNacosConfig(globalProperties = @NacosProperties(serverAddr = "${nacos.address}",namespace="${nacos.namespace}"))
@EnableNacosDiscovery(globalProperties = @NacosProperties(serverAddr = "${nacos.address}",namespace="${nacos.namespace}"))
@NacosPropertySource(dataId = "${nacos.dataId}",autoRefreshed=true)
public class EsMobileClientLauncherApplication
```

_不生效的根本原因应该是 nacos 作为注册中心的时候，消费者端没有订阅 routers:xxx 节点导致的；2.7 以上的版本建议使用动态配置中心来做服务治理_
消费者端没有订阅 routers:xxx 节点  这个怎么订阅，上面的配置不能做到订阅么？
动态配置中心，nacos本身就应该算使用了动态配置中心了吧

**Comment by manbab** [comment]
debug了一下，发现
![image](https://user-images.githubusercontent.com/3623460/66748188-247c5800-eeb9-11e9-988c-8e03934a203e.png)
使用的nacos
也订阅了routers
![image](https://user-images.githubusercontent.com/3623460/66748329-7de48700-eeb9-11e9-9aee-626b587ec2d3.png)

再注册完consumers以后，也进行了订阅了

**Comment by manbab** [comment]
org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(URL url, NotifyListener listener)
会循环Categories
![image](https://user-images.githubusercontent.com/3623460/66754260-2c8fc400-eec8-11e9-982d-6a5beb7fe54e.png)
org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(URL url, NotifyListener listener, Set<String> serviceNames)
里没有循环Categories
![image](https://user-images.githubusercontent.com/3623460/66754344-5812ae80-eec8-11e9-8fc8-0fb81af78620.png)
这个是dubbo2.7.3本身的bug么？

**Comment by kexianjun** [comment]
> routers:com.everstar.mobile.service.INetEventService:1.0.0:
> 这个地方正常了，
> 调用时206还是会执行
> 我的配置文件如下
> 
> > nacos.address = 192.168.1.199:8848
> > nacos.dataId = dubbo-EsMobileClientLauncher-cousumer
> > nacos.namespace = fd4c2b5d-3649-4558-b85f-50b2f0eb6c4a
> > dubbo.registry.address = nacos://192.168.1.199:8848?namespace=fd4c2b5d-3649-4558-b85f-50b2f0eb6c4a
> 
> 我的启动注解如下
> 
> ```
> @SpringBootApplication
> @Configuration
> //@EnableCaching
> //@EnableSwagger2
> @EnableDubbo(scanBasePackages = "com") 
> @EnableNacosConfig(globalProperties = @NacosProperties(serverAddr = "${nacos.address}",namespace="${nacos.namespace}"))
> @EnableNacosDiscovery(globalProperties = @NacosProperties(serverAddr = "${nacos.address}",namespace="${nacos.namespace}"))
> @NacosPropertySource(dataId = "${nacos.dataId}",autoRefreshed=true)
> public class EsMobileClientLauncherApplication
> ```
> 
> _不生效的根本原因应该是 nacos 作为注册中心的时候，消费者端没有订阅 routers:xxx 节点导致的；2.7 以上的版本建议使用动态配置中心来做服务治理_
> 消费者端没有订阅 routers:xxx 节点 这个怎么订阅，上面的配置不能做到订阅么？
> 动态配置中心，nacos本身就应该算使用了动态配置中心了吧

动态配置中心要配置的，参考 http://dubbo.apache.org/zh-cn/docs/user/configuration/config-center.html

**Comment by kexianjun** [comment]
> org.apache.dubbo.registry.zookeeper.ZookeeperRegistry.doSubscribe(URL url, NotifyListener listener)
> 会循环Categories
> ![image](https://user-images.githubusercontent.com/3623460/66754260-2c8fc400-eec8-11e9-982d-6a5beb7fe54e.png)
> org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(URL url, NotifyListener listener, Set serviceNames)
> 里没有循环Categories
> ![image](https://user-images.githubusercontent.com/3623460/66754344-5812ae80-eec8-11e9-8fc8-0fb81af78620.png)
> 这个是dubbo2.7.3本身的bug么？

这个不太清楚 nacos 这么写的意图，结果就是 routers:xxx 这个节点没有订阅，你可以去 dubbo 下面提个 issue 问一下

**Comment by manbab** [comment]
我修改了下配置，采用官方的动态配置中心的配置方式来试试

**Comment by manbab** [comment]
换成配置中心以后，发现com.everstar.mobile.service.INetEventService:1.0.0.condition-router，，这个地方少了个：符号应该再版本号后加个：，变成com.everstar.mobile.service.INetEventService:1.0.0:.condition-router

**Comment by manbab** [comment]
动态配置中心时监听的com.everstar.mobile.service.INetEventService:1.0.0:.condition-router这样一个配置

**Comment by kexianjun** [comment]
> 动态配置中心时监听的com.everstar.mobile.service.INetEventService:1.0.0:.condition-router这样一个配置

条件路由，服务维度的时候务必填写完整的服务名如下：
> xxxServiceName:version:group

version 或 group 为空的时候可不填(: 号务必保留)

**Comment by manbab** [comment]
我试一下，感觉上很奇怪，不会自动补充么
