### ISSUE TITLE
项目编译报错

### ISSUE THREAD

**Issue by CaoRookie** [apache/dubbo-admin#526]
环境：idea 2019.2.1
jdk: 1.8_181
maven: 3.6.1

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (process-resource-bundles) on project dubbo-admin: Execution process-resource-bundles of goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process failed: A required class was missing while executing org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process: org/apache/commons/collections/ExtendedProperties

**Comment by htynkn** [comment]
Currently ci pass for whole project. more detail refer to https://github.com/apache/dubbo-admin/blob/develop/.github/workflows/ci.yml
