### ISSUE TITLE
项目显示起来了，然而访问localhost:8080无效

### ISSUE THREAD

**Issue by GisDeng** [apache/dubbo-admin#533]
项目显示起来了，然而访问localhost:8080无效。但是访问swagger却又显示；
此外，在mvn celan package的时候，一直没结束
![image](https://user-images.githubusercontent.com/30002851/67615593-ea884b80-f800-11e9-8769-b14c63827d50.png)

**Comment by sunwulovelove1** [comment]
我遇到了一个情况和你很像，就是项目启动卡在哪里，我以为是 启动已完成但是我部署的有问题。。

实际上是，我连接的公司的zookeeper ,上面的服务太多了，一直在订阅。。。我并没有看到develop分在这里打印日志

我切换到master分支，看到了日志，才发现这个问题

**Comment by GisDeng** [comment]
我的admin能起来。但是package的时候一直卡着不动。你是怎么解决的 @sunwulovelove1

**Comment by sunwulovelove1** [comment]
我换了一个本地的zk（里面注册服务很少），很快启动起来了，确认了程序没问题。




山高月小，水落石出。
在2019年10月31日 21:43，GisDeng 写道：

我的admin能起来。但是package的时候一直卡着不动。你是怎么解决的 @sunwulovelove1
