### ISSUE TITLE
dubbo-admin master版本问题：配置dubbo.provider.group=show后点击接口报错

### ISSUE THREAD

**Issue by pi-chow** [apache/dubbo-admin#540]
* 点击图片
![image](https://user-images.githubusercontent.com/30309613/68448147-819bcd00-021d-11ea-8327-8d4e98c03169.png)
*issue 效果
![image](https://user-images.githubusercontent.com/30309613/68447925-b2c7cd80-021c-11ea-883b-3d0e55465c43.png)
* 判断：dubbo-admin master 前端路由直接按照/{service}，未添加/{group}/{service}处理，请问，后续还会处理吗

**Comment by KeRan213539** [comment]
This problem has been fixed by #669.
Please feel free to reopen it if you have any question.
