### ISSUE TITLE
dubbo-admin怎么启用服务统计功能??急

### ISSUE THREAD

**Issue by lfc8912** [apache/dubbo-admin#541]
服务统计中输入IP搜索Metrics信息，输入ip后，报错:
 System Error, please try again later! Message:Failed to invoke remote method: getMetricsByGroup, provider: dubbo://127.0.0.1:20880/org.apache.dubbo.monitor.MetricsService?application=dubbo-admin&cache=true&interface=org.apache.dubbo.monitor.MetricsService&lazy=false&pid=5512&register.ip=169.254.182.37&remote.application=&revision=2.7.3&scope=remote&side=consumer&sticky=false, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.monitor.MetricsService:20880 in [com.lfc.dubbo.service.DemoService:1.0.0:20880], may be version or group mismatch , channel: consumer: /169.254.182.37:62189 --> provider: /169.254.182.37:20880, message:RpcInvocation [methodName=getMetricsByGroup, parameterTypes=[class java.lang.String], arguments=[dubbo], attachments={path=org.apache.dubbo.monitor.MetricsService, input=225, dubbo=2.0.2, interface=org.apache.dubbo.monitor.MetricsService, version=0.0.0}] org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.monitor.MetricsService:20880 in [com.lfc.dubbo.service.DemoService:1.0.0:20880], may be version or group mismatch , channel: consumer: /169.254.182.37:62189 --> provider: /169.254.182.37:20880, message:RpcInvocation [methodName=getMetricsByGroup, parameterTypes=[class java.lang.String], arguments=[dubbo], attachments={path=org.apache.dubbo.monitor.MetricsService, input=225, dubbo=2.0.2, interface=org.apache.dubbo.monitor.MetricsService, version=0.0.0}] at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:266) at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:127) at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102) at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193) at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by 632657122** [comment]
同问

**Comment by Leme34** [comment]
我用的Dubbo是2.7.18，对应最高可用dubbo-amin版本为0.3.0，摸着源码自己改好了，有完整的本地运行demo，供大家参考，详见https://github.com/Leme34/dubbo-spi-demo/tree/master/dubbo-admin
![1708596086266](https://github.com/apache/dubbo-admin/assets/32232194/f3fd2eb4-408d-4c2d-b667-8a2de7292706)
