### ISSUE TITLE
pom文件出现红色

### ISSUE THREAD

**Issue by maxiaodong58** [apache/dubbo-admin#544]
![image](https://user-images.githubusercontent.com/28079725/68866852-fac08600-072f-11ea-8139-d6502b5047a9.png)

**Comment by htynkn** [comment]
maven-assembly-plugin version 3.1.0 is existing in central repo (https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-assembly-plugin/3.1.0)
also this one is for release profile, you can ignore it.
