### ISSUE TITLE
mvn clean package打包时，提示curator包下的TestingZooKeeperMain这个测试类运行了2182端口占用

### ISSUE THREAD

**Issue by lazychen233** [apache/dubbo-admin#550]
INFO org.apache.curator.test.TestingZooKeeperMain - Could not start server. Waiting and trying one more time.
java.net.BindException: Address already in use
是不是依赖的curator里测试配置了地址端口，然后导致dubbo-admin引用过来时打包一直出错？还是是我哪里配置不对？server里的配置都按照文档改过了，改成自己的

**Comment by yuezxl** [comment]
mvn clean package -Dmaven.test.skip=true 跳过测试类启动
