### ISSUE TITLE
dubbo-admin-ui 怎么build（非dev）

### ISSUE THREAD

**Issue by zealotTL** [apache/dubbo-admin#551]
背景：前端小白，只是想用用新版dubbo-admin
问题：dubbo-admin-ui 的 `npm run dev`，能成功加载页面。`npm run build`，打开target/dist/index.html报错，F12发现是 引用文件用了绝对路径，改了config/index.js ->build->assetsPublicPath的值 “/” =》 "./"。还是报错（项目在G盘）：
`G:/static/OpenSans.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND`
`Access to XMLHttpRequest at 'file:///G:/api/dev/services`
求帮助~~~
===========================
Background: little white at the front, just want to use the new Dubbo admin
Problem: the 'NPM run dev' of Dubbo admin UI can load the page successfully. `NPM run build '. Open target / dist / index.html to report an error. F12 found that the absolute path was used for the reference file, and changed the value "/ =". / "of config / index.js - > build - > assetspublicpath. Or error report (items are on disk g):
`G:/static/OpenSans.css:1 Failed to load resource: net::ERR_FILE_NOT_FOUND`
`Access to XMLHttpRequest at 'file:///G:/api/dev/services`
Ask for help ~ ~

**Comment by htynkn** [comment]
you can try latest code with webpack 4
it should work
