### ISSUE TITLE
Dubbo admin Test don't supped Enum, 2.7.3

### ISSUE THREAD

**Issue by wuxiansen** [apache/dubbo-admin#554]
Dubbo 2.7.3
JDK 1.8
OS centos

System Error, please try again later! Message:Failed to invoke the method dataIndicator in the service org.apache.dubbo.rpc.service.GenericService. Tried 3 times of the providers [172.30.X.X9:20880] (1/1) from the registry ip:2282 on the consumer 192.168.xxx.32 using the dubbo version 2.7.3. Last error is: Failed to invoke remote method: $invoke, provider: dubbo://172.30.X.X9:20880/com.xxxx.xxx.xxxmethodName?anyhost=true&application=dubbo-admin&bean.name=ServiceBean:com.xxx.xxx.xx.Classname:1.0&check=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&interface=com.xxx.xxx.xxx.ClassName&lazy=false&methods=dataIndicator&pid=71406&register=true&register.ip=192.168.202.32&release=2.7.3&remote.application=app-name&revision=1.0&side=consumer&sticky=false&timestamp=1575370141164&version=1.0, cause: org.apache.dubbo.remoting.RemotingException: java.lang.IllegalArgumentException: `Cannot reflectively create enum objects java.lang.IllegalArgumentException: Cannot reflectively create enum objects at java.lang.reflect.Constructor.newInstance(Constructor.java:417) at `org.apache.dubbo.common.utils.PojoUtils.newInstance(PojoUtils.java:547) at org.apache.dubbo.common.utils.PojoUtils.realize0(PojoUtils.java:446) at org.apache.dubbo.common.utils.PojoUtils.realize0(PojoUtils.java:461) at org.apache.dubbo.common.utils.PojoUtils.realize(PojoUtils.java:205) at org.apache.dubbo.common.utils.PojoUtils.realize(PojoUtils.java:95) at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:85) at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38) at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41) at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82) at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:157) at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:152) at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102) at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193) at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51) at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:748)

**Comment by 632657122** [comment]
有啥解决方案了吗

**Comment by wuxiansen** [comment]
> 有啥解决方案了吗

临时解决的方式是： 在页面上选择 字符串类型，然后输入对应的值可以映射。😃
