### ISSUE TITLE
[login] add a switch to disable login

### ISSUE THREAD

**Issue by spawpaw** [apache/dubbo-admin#562]
considering to add a config to disable login? its annoyning that you need to login after few minutes of break when you are using dubbo-admin in dev environment.

for example:
```
admin.login.enable=false (default true)
```

**Comment by kexianjun** [comment]
If you do not want authority control, you can add the following config in you application.properties file
> admin.check.authority=false

**Comment by spawpaw** [comment]
thx, I just don't kown where to find the doc : ) 

why not add an `additional-spring-configuration-metadata.json` to META-INF?

**Comment by htynkn** [comment]
this project is not same as other project. this will not use as a third-party library. so add metadata.json is only for auto complete feature in IDE.

I have tried different IDE, only manually created file `spring-configuration-metadata.json` can trigger auto complete. and we can consider this file as a property document too.
