### ISSUE TITLE
dubbo-admin 编译报错node

### ISSUE THREAD

**Issue by Lanceff** [apache/dubbo-admin#563]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project dubbo-admin-ui: Could not extract the Node archive: Could not extract archive: 'E:\xxx\com\github\eirslett\node\9.11.1\node-9.11.1-win-x64.zip': zip END header not found -> [Help 1]

**Comment by biyuhao** [comment]
可能是网络问题，可以试下挂代理，并且将本地的`node-9.11.1-win-x64.zip`删掉重新下载再试下
