### ISSUE TITLE
dubbo admin v2.7.4是否支持guest用户？

### ISSUE THREAD

**Issue by PostgreSQL1989** [apache/dubbo-admin#566]
请问一下，新版的dubbo admin是否可以支持guest用户？
我修改了配置文件，设置了admin.guest.user.name和admin.guest.user.password参数，发现并没有生效。
如果可以支持guest用户，请问怎么配置？

**Comment by kexianjun** [comment]
不支持，目前没有做权限隔离，支持 guest 用户意义也不大

**Comment by PostgreSQL1989** [comment]
> 不支持，目前没有做权限隔离，支持 guest 用户意义也不大

好的，谢谢你的回复。
