### ISSUE TITLE
npm run build出现错误

### ISSUE THREAD

**Issue by STrongerLiang** [apache/dubbo-admin#580]
> dubbo-admin-frontend@1.0.0 build /root/incubator-dubbo-ops/dubbo-admin-frontend
> node build/build.js

⠼ building for production...
<--- Last few GCs --->

[3650:0x3aa83f0]   149203 ms: Mark-sweep 475.4 (493.0) -> 471.9 (493.2) MB, 1000.7 / 0.0 ms  (average mu = 0.101, current mu = 0.022) allocation failure scavenge might not succeed
[3650:0x3aa83f0]   150316 ms: Mark-sweep 475.7 (493.2) -> 472.3 (493.5) MB, 1091.4 / 0.0 ms  (average mu = 0.059, current mu = 0.019) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13a71b9]
Security context: 0x3f84ae5008d1 <JSObject>
    1: getArg [0x19bc5834f359] [/root/incubator-dubbo-ops/dubbo-admin-frontend/node_modules/source-map/lib/util.js:~18] [pc=0x23f07963709f](this=0x19bc5834f1d9 <Object map = 0x1166173365d9>,0x2aae7f6a8f29 <Mapping map = 0x22b84f903ea9>,0x120c1a0475e9 <String[#12]: originalLine>,0x1e6a16b401b9 <null>)
    2: /* anonymous */(aka /* anonymous */) [0x9df77c0e1] [0x1e...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200223.135131.3650.0.001.json
Node.js report completed
 1: 0x9ef190 node::Abort() [node]
 2: 0x9f13b2 node::OnFatalError(char const*, char const*) [node]
 3: 0xb5da9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb5de19 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd0a765  [node]
 6: 0xd0adf6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd1760a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd18515 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd1afcc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xce19bb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x10246ce v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x13a71b9  [node]
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! dubbo-admin-frontend@1.0.0 build: `node build/build.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the dubbo-admin-frontend@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-02-23T05_51_32_248Z-debug.log

**Comment by STrongerLiang** [comment]
这是在incubator-dubbo-ops中执行 mvn clean package 时 发生的错误

[INFO] --- frontend-maven-plugin:1.6:npm (npm install) @ dubbo-admin-frontend ---
[INFO] Running 'npm install' in /root/incubator-dubbo-ops/dubbo-admin-frontend
[WARNING] npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
[WARNING] npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[WARNING] npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[WARNING] npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[WARNING] npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[WARNING] npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[INFO] 
[INFO] > core-js@2.6.11 postinstall /root/incubator-dubbo-ops/dubbo-admin-frontend/node_modules/core-js
[INFO] > node -e "try{require('./postinstall')}catch(e){}"
[INFO] 
[INFO] Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
[INFO] 
[INFO] The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
[INFO] > https://opencollective.com/core-js 
[INFO] > https://www.patreon.com/zloirock 
[INFO] 
[INFO] Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
[INFO] 
[INFO] 
[INFO] > ejs@2.7.4 postinstall /root/incubator-dubbo-ops/dubbo-admin-frontend/node_modules/ejs
[INFO] > node ./postinstall.js
[INFO] 
[INFO] Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)
[INFO] 
[INFO] 
[INFO] > uglifyjs-webpack-plugin@0.4.6 postinstall /root/incubator-dubbo-ops/dubbo-admin-frontend/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
[INFO] > node lib/post_install.js
[INFO] 
[ERROR] npm notice created a lockfile as package-lock.json. You should commit this file.
[WARNING] npm WARN ajv-errors@1.0.1 requires a peer of ajv@>=5.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
[INFO] added 1360 packages in 48.068s
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:npm (npm run build) @ dubbo-admin-frontend ---
[INFO] Running 'npm run build' in /root/incubator-dubbo-ops/dubbo-admin-frontend
[INFO] 
[INFO] > dubbo-admin-frontend@1.0.0 build /root/incubator-dubbo-ops/dubbo-admin-frontend
[INFO] > node build/build.js
[INFO] 

执行到 node build/build.js 后就不运行了，单独在此 incubator-dubbo-ops/dubbo-admin-frontend 目录下执行 npm run build 后就出现了上面的问题

**Comment by biyuhao** [comment]
请pull下最新develop分支代码，mvn clean之后重新打包
