### ISSUE TITLE
连接zk超时？

### ISSUE THREAD

**Issue by kevin8719** [apache/dubbo-admin#590]
Connection timed out for connection string (127.0.0.1:2181) and timeout (15000) / elapsed (31089)
KeeperErrorCode = ConnectionLoss

**Comment by biyuhao** [comment]
从看输出上看是这个意思

**Comment by kevin8719** [comment]
没人维护了吧

**Comment by htynkn** [comment]
可以通过```admin.registry.address```属性指定zookeeper地址

**Comment by icankeep** [comment]
#548
