### ISSUE TITLE
RegistryServerSync内存泄漏问题

### ISSUE THREAD

**Issue by spilledyear** [apache/dubbo-admin#598]
在 org.apache.dubbo.admin.service.RegistryServerSync#notify 方法中， 以下核心代码

if (URL_IDS_MAPPER.containsKey(url.toFullString())) {
    ids.put(URL_IDS_MAPPER.get(url.toFullString()), url);
} else {
    String md5 = CoderUtil.MD5_16bit(url.toFullString());
    ids.put(md5, url);
    URL_IDS_MAPPER.putIfAbsent(url.toFullString(), md5);
}

比如同一个服务实例执行 上线 =》 下线 =》 上线 =》 ，在 URL_IDS_MAPPER 会产生两个元素，其中只有一个有效，另一个无效。 如果不断执行这个动作，同一个服务实例会产生多个无效对象，如果服务量比较大，会导致应用占用的内存越来越大

**Comment by aworker** [comment]
是的，确实有你说的这个问题， 除非能感知每个服务的变化（如url从有效到无效，url代表的服务名称改变，url代表的服务的协议变化），否则就有你说的问题， 但是感知url中到底是同一个服务的变化（比如protocol变化），还是新增加了一个服务几乎是不可能完成的。所以建议把URL_IDS_MAPPER 这个缓存给去掉，牺牲点md5的计算性能，或者直接用guava缓存吧。

**Comment by spilledyear** [comment]
是的，目前我是把这个URL_IDS_MAPPER关闭了。那我先把这个关了

**Comment by liuwenwu122** [comment]
在服务下线通知的时候，可以根据 registryCache 保存的  md5 值去清除 URL_IDS_MAPPER 中对应的值嘛
