### ISSUE TITLE
load is warning

### ISSUE THREAD

**Issue by l343765828** [apache/dubbo-admin#600]
![image](https://user-images.githubusercontent.com/49823736/80602322-8b321f00-8a61-11ea-89bb-b7298cac3393.png)
What is the load？

**Comment by l343765828** [comment]
dubbo?

**Comment by htynkn** [comment]
refer to: https://github.com/apache/dubbo/blob/2.6.x/dubbo-common/src/main/java/com/alibaba/dubbo/common/status/support/LoadStatusChecker.java

it's system load
