### ISSUE TITLE
Running 'npm install' 那里也太慢了

### ISSUE THREAD

**Issue by MelancholyAstronaut** [apache/dubbo-admin#606]
真的很慢

**Comment by htynkn** [comment]
这个步骤在CI大概需要30秒。
检查下网络或者看下卡在哪一步吧

**Comment by MelancholyAstronaut** [comment]
我自己安装npm,执行npm install 和 npm run dev 这两个指令

**Comment by htynkn** [comment]
<img width="447" alt="屏幕快照 2020-05-17 下午5 14 06" src="https://user-images.githubusercontent.com/659135/82140540-d6ba3a80-9861-11ea-87bc-f2137e1dc305.png">

我本地运行大概下载加编译70s（mac + node v10），本身应该没问题。看下是不是网络问题吧。
