### ISSUE TITLE
Dubbo Admin  Docker-Compose方式安装如何设置账号密码

### ISSUE THREAD

**Issue by RobertoHuang** [apache/dubbo-admin#620]
你好 请教一下 Dubbo Admin Docker-Compose方式安装如何设置账号密码？

**Comment by liangzhiyong** [comment]
dubbo-admin 默认账号信息是写死在 jar包里的,
/BOOT-INF/classes/application.properties 里面的:
admin.root.user.name=root
admin.root.user.password=root
如果想通过docker-compose 方式指定的话，即启动java -jar 时指定下 admin.root.user.name 和 admin.root.user.password的值即可。

**Comment by RobertoHuang** [comment]
我看官方提供的docker-compose好像没提供这两个环境变量的配置

https://hub.docker.com/r/apache/dubbo-admin 这个是docker hub的地址 麻烦看一下

**Comment by htynkn** [comment]
目前正式发布的只有0.1.0，并不支持登陆验证，可以自行构建develop分支的最新代码。
具体配置项目参考 liangzhiyong 的评论

**Comment by htynkn** [comment]
related: https://github.com/apache/dubbo-admin/issues/529
