### ISSUE TITLE
请问是不是dockerhub上的版本太老了，试了很久2.7.0以上的都显示不出元数据

### ISSUE THREAD

**Issue by Winble** [apache/dubbo-admin#634]
请问是不是dockerhub上的版本太老了，试了很久2.7.0以上的都显示不出元数据

**Comment by htynkn** [comment]
dokcerhub上只有0.1.0版本，目前新版本还没有发布。
建议自行构建develop分支，也可以参考 https://github.com/apache/dubbo-admin/blob/develop/docker/latest/Dockerfile 自行构建DockerImage
