### ISSUE TITLE
是否可以支持不用账号和密码就能进入dubbo-admin？

### ISSUE THREAD

**Issue by Donald-Chun** [apache/dubbo-admin#637]
dubbo-admin一般公司内部网络用，实际用不着每次都要拿账号和密码登录。

是否可以添加一项功能：可以把使用账号和密码登录的功能关掉？

**Comment by htynkn** [comment]
指定属性 admin.check.authority 为 false 即可

**Comment by Donald-Chun** [comment]
谢谢，配置有效，搞定了。
