### ISSUE TITLE
dubbo2.5的版本用哪个dubbo-admin?这个好像不支持2.5

### ISSUE THREAD

**Issue by jackbauer123** [apache/dubbo-admin#656]
- [ ] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: xxx
* Registry center detail (type and version): xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. xxx
2. xxx
3. xxx

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by htynkn** [comment]
previous version is on master branch:
https://github.com/apache/dubbo-admin/tree/master
