### ISSUE TITLE
我生成不了jar包，报错

### ISSUE THREAD

**Issue by shifeng-git** [apache/dubbo-admin#657]
* Dubbo version: xxx
* Registry center detail (type and version): xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1. mvn clean package这个是生成哪个文件的jar包？是dubbo-admin-distribution这个吗？会报错
[ERROR] Failed to execute goal on project dubbo-admin-distribution: Could not resolve dependencies for project org.apache:dubbo-admin-distribution:jar:0.2.0-SNAPSHOT: The following artifacts could not be resolved: org.apache:dubbo-admin-ui:jar:0.2.0-SNAPSHOT, org.apache:dubbo-admin-server:jar:0.2.0-SNAPSHOT: Failure to find org.apache:dubbo-admin-ui:jar:0.2.0-SNAPSHOT in https://repository.apache.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots.https has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by htynkn** [comment]
1.是dubbo-admin-distribution中的文件
2.当前CI系统是能够正常构建的，考虑到apache snapshot repo从网络访问可能有一定问题，可以使用其他maven镜像，或者加强网络
