### ISSUE TITLE
启动dubbo-admin-ui出现的错误

### ISSUE THREAD

**Issue by demosunguohua** [apache/dubbo-admin#670]
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo admin version：0.2.0-SNAPSHOT
* Registry center detail (type and version): https://registry.npm.taobao.org 
* Operating System version: Mac OS BigSur 11
* Java version: java1.8

### Steps to reproduce this issue

1. git clone https://github.com/apache/dubbo-admin.git
2. 在dubbo-admin-ui下，执行npm install

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

安装成功

### Actual Result

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npm.taobao.org/@xtuc/long/-/long-4.2.2.tgz - [not_found] document not found
npm ERR! 404 
npm ERR! 404  '@xtuc/long@https://registry.npm.taobao.org/@xtuc/long/-/long-4.2.2.tgz' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sunguohua/.npm/_logs/2020-12-03T03_32_51_881Z-debug.log

**Comment by KeRan213539** [comment]
不使用淘宝源试试呢?

**Comment by demosunguohua** [comment]
> 不使用淘宝源试试呢?

感谢你的答复。我已经找到解决的方法了。
一开始换了个源还是不行，最后用yarn安装解决了问题。

**Comment by KeRan213539** [comment]
> > 不使用淘宝源试试呢?
> 
> 感谢你的答复。我已经找到解决的方法了。
> 一开始换了个源还是不行，最后用yarn安装解决了问题。

客气了,解决就行.  :)

**Comment by KeRan213539** [comment]
Please feel free to reopen it if you have any question.
