### ISSUE TITLE
服务端重启后自动跳转登录页的问题

### ISSUE THREAD

**Issue by KeRan213539** [apache/dubbo-admin#697]
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo admin version: 0.3.0-SNAPSHOT(develop分支)
* Registry center detail (type and version): zk
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

1. 打开某个页面后(例如: http://localhost:8080/#/governance/routingRule?service=%2a), 重启服务端
2. 在之前打开的页面刷新
3. 页面会自动跳转到登录页面,但是地址不正确,为: http://localhost:8080/#/governance/login?redirect=%2Fgovernance%2Flogin%3Fredirect%3D%252Fgovernance%252Flogin%253Fredirect%253D%25252Fgovernance%25252FroutingRule%25253Fservice%25253D%2525252a
4. 手工修改第三步中的连接,把其中的 "governance" 去掉后,显示出登录界面
5. 输入帐号密码后点登录,跳转的地址不正确,为: http://localhost:8080/#/governance/login?redirect=%2Fgovernance%2Flogin%3Fredirect%3D%252Fgovernance%252FroutingRule%253Fservice%253D%25252a

但是如果重启服务端后,直接新窗口打开第一步中的连接,就正常. 仅先打开某页面,重启服务端后刷新页面才会出现

### Expected Result

需要登录时跳转到正确的地址,并且登录后回到之前的页面

**Comment by tzr164** [comment]
@i will solve it@
