### ISSUE TITLE
main-EventThread lock住是正常现象吗

### ISSUE THREAD

**Issue by chenshun00** [apache/dubbo-admin#698]
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* curator-framework :  4.0.1
* Registry center detail (type and version): xxx
* Operating System version: Linux
* Java version: jdk  1.8

### Steps to reproduce this issue

![image](https://user-images.githubusercontent.com/26037282/109440937-c250d280-7a6e-11eb-8f11-436b3045f40a.png)

![image](https://user-images.githubusercontent.com/26037282/109440942-c7158680-7a6e-11eb-8972-ac1f2e4297c7.png)

dubbo-admin 回调的notify不执行了，看堆栈就是上述的显示，请问下这个是不是正常的呢

**Comment by KeRan213539** [comment]
这个看起来应该是 zk 的问题,能具体定位吗?

**Comment by chenshun00** [comment]
感觉是网络交互的问题，不排除zk的问题，我还得在看看

**Comment by KeRan213539** [comment]
> 感觉是网络交互的问题，不排除zk的问题，我还得在看看

有结果还请反馈一下

**Comment by chenshun00** [comment]
我先关了，刚觉还是当初的可能存在网络问题，等再出现了，我在打开好了，现在的堆栈正常的

![image](https://user-images.githubusercontent.com/26037282/109592098-ae2dd380-7b49-11eb-91f0-adc68c0e19f7.png)

**Comment by KeRan213539** [comment]
ok~
