### ISSUE TITLE
nacos作为dubbo的注册中心 看不到元数据

### ISSUE THREAD

**Issue by zlygit** [apache/dubbo-admin#703]
1.nacos作为dubbo的注册中心 看不到元数据 服务能看到
根据 https://github.com/apache/dubbo-admin/pull/700 
好像3月一号左右已经解决了这个问题 不知道是在哪个分支上
本地下载的develop的dubboAdmin已经跟新到最新版（Thu Mar 4 16:52:11 2021） 还是看不到元数据信息
2.dubbo的元数据信息在nacos的配置列表中一直存在 ，不会自动删除吗？

**Comment by neal-wyz** [comment]
> 1.nacos作为dubbo的注册中心 看不到元数据 服务能看到
> 根据 #700
> 好像3月一号左右已经解决了这个问题 不知道是在哪个分支上
> 本地下载的develop的dubboAdmin已经跟新到最新版（Thu Mar 4 16:52:11 2021） 还是看不到元数据信息
> 2.dubbo的元数据信息在nacos的配置列表中一直存在 ，不会自动删除吗？

我也遇到这个问题，后面我检查nacos时发现配置管理中接口元数据的group是dubbo而不是服务管理中的DEFAULT_GROUP，然后我修改了admin.metadata-report.group=dubbo，就可以查看到元数据了

**Comment by Y-Aron** [comment]
修改配置
#group
admin.registry.group=DEFAULT_GROUP
admin.config-center.group=dubbo
admin.metadata-report.group=dubbo

**Comment by Y-Aron** [comment]
修改配置
#group
admin.registry.group=DEFAULT_GROUP
admin.config-center.group=dubbo
admin.metadata-report.group=dubbo

**Comment by zlygit** [comment]
试了还是不行 dubboAdmin会提示无元数据信息，请升级至Dubbo2.7及以上版本，或者查看application.properties中关于config center的配置
-----dubbo admin start---
admin.registry.address=nacos://127.0.0.1:8848
admin.config-center=nacos://127.0.0.1:8848
admin.metadata-report.address=nacos://127.0.0.1:8848
admin.root.user.name=root
admin.root.user.password=root
#group
admin.registry.group=dubbo
admin.config-center.group=dubbo
admin.metadata-report.group=dubbo
---dubboadmin end---

---nacos dubbo properties start ---
dubbo.application.name=dubbo_demo_provider
dubbo.registry.address=nacos://127.0.0.1:8848
dubbo.registry.use-as-config-center=true
dubbo.registry.group=dubbo
dubbo.scan.base-packages=com.example.demo.serviceImpl

dubbo.protocol.name=dubbo
dubbo.protocol.port=28080

dubbo.metadata-report.group=dubbo
dubbo.metadata-report.address=nacos://127.0.0.1:8848
---nacos dubbo properties end---
在nacos 后台可以看到 配置列表 2条数据 
com.example.demo.api.TestService:1.0.0:dubbo:provider:dubbo_demo_provider （DataId）
dubbo (groudId)
dubbo_demo_provider
mapping-com.example.demo.api.TestService
服务列表一条数据
providers:com.example.demo.api.TestService:1.0.0:dubbo | dubbo
 
dubboAdmin 元数据还是显示不了

**Comment by Y-Aron** [comment]
> 试了还是不行 dubboAdmin会提示无元数据信息，请升级至Dubbo2.7及以上版本，或者查看application.properties中关于config center的配置
> -----dubbo admin start---
> admin.registry.address=nacos://127.0.0.1:8848
> admin.config-center=nacos://127.0.0.1:8848
> admin.metadata-report.address=nacos://127.0.0.1:8848
> admin.root.user.name=root
> admin.root.user.password=root
> #group
> admin.registry.group=dubbo
> admin.config-center.group=dubbo
> admin.metadata-report.group=dubbo
> ---dubboadmin end---
> 
> ---nacos dubbo properties start ---
> dubbo.application.name=dubbo_demo_provider
> dubbo.registry.address=nacos://127.0.0.1:8848
> dubbo.registry.use-as-config-center=true
> dubbo.registry.group=dubbo
> dubbo.scan.base-packages=com.example.demo.serviceImpl
> 
> dubbo.protocol.name=dubbo
> dubbo.protocol.port=28080
> 
> dubbo.metadata-report.group=dubbo
> dubbo.metadata-report.address=nacos://127.0.0.1:8848
> ---nacos dubbo properties end---
> 在nacos 后台可以看到 配置列表 2条数据
> com.example.demo.api.TestService:1.0.0:dubbo:provider:dubbo_demo_provider （DataId）
> dubbo (groudId)
> dubbo_demo_provider
> mapping-com.example.demo.api.TestService
> 服务列表一条数据
> providers:com.example.demo.api.TestService:1.0.0:dubbo | dubbo
> 
> dubboAdmin 元数据还是显示不了

admin.registry.group=dubbo 改成DEFAULT_GROUP

**Comment by zlygit** [comment]
改了dubboAdmin的配置也不行 我的demo为https://gitee.com/pse/dubbo_nacos_myparent.git  可能更版本有关系吗 我用的是比较新的版本 学习下  这个问题困扰了好久

**Comment by nickwongwong** [comment]
经测试和调试，
dubbo 2.7 + nacos bug有点多，服务测试和服务统计不可用，服务列表查看可用
#694

**Comment by KeRan213539** [comment]
#530 #694

**Comment by zlygit** [comment]
好的 我试试 多谢大神指点

**Comment by conglaw** [comment]
@zlygit 你解决了问题了吗，我试了上述的方案，依然不行
