### ISSUE TITLE
Dubbo Admin provides service mock ability

### ISSUE THREAD

**Issue by AlbumenJ** [apache/dubbo-admin#757]
Add the service mock capability to Admin to provide consumers with the ability to test before the provider's development is completed. Called to consumers by simulating the data returned by the provider.

Reference realization ideas/main points (if you have different ideas, you can also put forward them):
• Add database support (MySQL) to save mock configuration
• It is recommended to use Mybatis (plus) as the ORM and Druid as the connection pool, try to use standard SQL, and try to ensure that you can use other databases with a different driver
• Admin provides the configuration function of rules, user-specified interface (full package path), method name, return type (basic data types such as String, int, long and complex types), return value (complex type users provide JSON, before returning JSON is converted to Map and returned, and PojoUtils is used in the Filter on the frame side to restore it to the type returned by the method), and the return method (asynchronous/synchronous) is configured.
• Add a provider service (MockService) on the Admin side and register it in the registry. The service reads the rules and returns the corresponding data, receiving interface, method name, and arbitrary method parameters according to the rules, finds the corresponding configuration according to the interface and method name, and generates the return data according to the configuration
• Add consumer Filter and switch configuration on Dubbo frame side (default off). After the switch is turned on, the request will be sent to MockService through Filter

Project requirements:
- Complete the service mock function
- Provide learning and use cases based on the knowledge-based hands-on laboratory

Skills requirement:
- Proficiency in Java
- Proficiency in using relevant front-end tools
- Familiar with Dubbo Filter mechanism

在 Admin 中增加服务 Mock 能力，用于在提供者开发完成前给消费者提供测试的能力。通过模拟提供者返回的数据的方式给消费者调用。

参考实现思路/要点（如果有不同思路也可以提出来）：
• 增加数据库支持（MySQL）以保存 Mock 的配制
• 建议使用 Mybatis（plus）作为 ORM，Druid 作为连接池，尽量使用标准 SQL，尽量保证能换个驱动就能使用其他数据库
• Admin 提供规则的配制功能，用户指定接口（完整包路径），方法名，返回类型（String，int，long 等基础数据类型及复杂类型），返回值（复杂类型用户提供JSON，在返回前把 JSON 转为 Map 返回，在框架侧的 Filter 中利用PojoUtils 还原为方法返回的类型），返回方式 （异步/同步）等配制。
• Admin 侧增加一个提供者服务（MockService）并注册到注册中心中。该服务通过读取规则并根据规则返回对应的数据、接收接口、方法名、任意方法参数，根据接口和方法名找到对应的配制,并根据配制生成返回数据
• Dubbo 框架侧增加消费者 Filter，和开关配制（默认关闭），开关开启后通过 Filter 把请求发送到 MockService

产出要求：
- 完成服务 Mock 功能
- 提供基于知行动手实验室的学习使用用例

技术要求：
- 熟练使用 Java
- 熟练使用相关前端工具
- 熟悉 Dubbo Filter 机制

**Comment by brotherlu-xcq** [comment]
Hi, guys. I want to work on this new feature. could you assign it to me?

**Comment by brotherlu-xcq** [comment]
@KeRan213539 @AlbumenJ @haoyann  I have made a design about this feature, could you review it and  give me some feedback?https://www.yuque.com/docs/share/ad0ba48c-2cba-4505-af09-1ef596a685f1?# 《Dubbo提供服务Mock能力》

**Comment by KeRan213539** [comment]
@brotherlu-xcq Hi, I'm glad you can contribute on dubbo and claim this issue. I replied some contents in the scheme you provided.
