### ISSUE TITLE
使用dubbo-go注册消费者服务后，zookeeper里的注册信息是没问题的，但是dubbo-admin显示提供者信息异常

### ISSUE THREAD

**Issue by shuoshadow** [apache/dubbo-admin#762]
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo Admin version: xxx
* Registry center detail (type and version): xxx
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

1、zookeeper中的提供者信息
![image](https://user-images.githubusercontent.com/10016360/118631747-60e50800-b802-11eb-935f-82b3ecac9fbe.png)

2、zookeeper中的消费者信息
![image](https://user-images.githubusercontent.com/10016360/118631830-74906e80-b802-11eb-8be6-5ed70396423d.png)

以上信息中，192.168.99.29、192.168.99.74是提供者ip没有问题、10.0.116.170是消费者

dubbo-admin中的信息：
![image](https://user-images.githubusercontent.com/10016360/118634521-30eb3400-b805-11eb-9b79-ac0c860eaff2.png)

![image](https://user-images.githubusercontent.com/10016360/118634645-58da9780-b805-11eb-8b46-1d0f4eeef8ad.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by shuoshadow** [comment]
params:
      category: "consumers"

reference config 增加如上配置

**Comment by drama10096** [comment]
reference config 增加如上配置params:   category: "consumers" 具体是在？？？
