### ISSUE TITLE
dubbo2.7.8 nacos 1.4.0 服务能正常访问,dubbo后台无法看到服务列表

### ISSUE THREAD

**Issue by waxJava2615** [apache/dubbo-admin#786]
配置如下：
在NACOS中新建配置dubbo.properties如下：
![image](https://user-images.githubusercontent.com/56405898/126766502-6e40986d-2d56-4b94-9d53-0cdeadba6f97.png)
值
dubbo.registry.address=nacos://192.168.216.151:8848?group=dubbo&namespace=f5734794-1e5d-49e1-8fad-e7c2e62075b4&username=nacos&password=nacos
dubbo.metadata-report.address=nacos://192.168.216.151:8848?group=dubbo&namespace=f5734794-1e5d-49e1-8fad-e7c2e62075b4&username=nacos&password=nacos

修改dubbo-admin配置,使用的是推荐配置：
![image](https://user-images.githubusercontent.com/56405898/126766562-08773b2e-97c3-4290-a689-290db1dec49b.png)

DUBBO后台服务列表空；
nacos服务列表有服务,消费者能正常调用：
![image](https://user-images.githubusercontent.com/56405898/126766773-b6510480-72cb-4561-80ca-2e8a09dea480.png)

**Comment by waxJava2615** [comment]
![Uploading image.png…]()

**Comment by waxJava2615** [comment]
当项目中DUBBO文件设置成：
![image](https://user-images.githubusercontent.com/56405898/126767345-f9fb233f-26b2-420e-9fc9-088cd5db4c33.png)
在nacos配置中可以看到多出2个配置:
![image](https://user-images.githubusercontent.com/56405898/126767459-70144794-8bf0-474d-ac7a-20a1ea163139.png)

**Comment by haoyann** [comment]
`dubbo-admin` 这边的配置也将 `namespace` 加上。

**Comment by waxJava2615** [comment]
> `dubbo-admin` 这边的配置也将 `namespace` 加上。

用上了出来了一堆服务 和配置。。。。 看着怪怪的;当 我吧注册地址换成
![image](https://user-images.githubusercontent.com/56405898/127585584-1384e75e-7f31-486d-8422-8f98ebc59e6a.png)
时，admin后台又看不到列表了。

**Comment by haoyann** [comment]
`用上了出来了一堆服务 和配置` 是什么意思？

**Comment by waxJava2615** [comment]
> `用上了出来了一堆服务 和配置` 是什么意思？
我是新手，所以问题有点多整合的时候；
生产者配置：
![image](https://user-images.githubusercontent.com/56405898/128300635-63d39783-f734-4c11-a5e5-cc9345ce3af0.png)
消费者配置：
![image](https://user-images.githubusercontent.com/56405898/128300681-f2ffbfbe-ff75-440e-8d27-e56d6882c5e6.png)
nacos配置列表：
![image](https://user-images.githubusercontent.com/56405898/128300824-87b0698e-4361-44f3-aaec-7f5b11b9f8e3.png)
nacos服务列表：
![image](https://user-images.githubusercontent.com/56405898/128300881-d8f0b16b-6aba-41d0-9847-3c0a568e49f1.png)
使用IDEA启动服务提供者和消费者，访问时出现：
![image](https://user-images.githubusercontent.com/56405898/128301014-ea028196-1b7e-49d0-be11-d797f59524b1.png)

当前环境：vm:部署NACOS dubbo  NGINX      VM网络模式: 桥接模式

消费者异常,获取不到服务者。
No provider available from registry nacos.wax.com:80 for service wax-demo-order-tcc/com.wax.tcc.order.interfaces.facade.dubbo.IOrderDubboService:1.0.0 on consumer 192.168.0.200 use dubbo version 2.7.8, please check status of providers(disabled, not registered or in blacklist).

**Comment by waxJava2615** [comment]
能访问了 但是dubbo后台服务列表是空的。看不懂了   要不你们能出一个DEMO吗？  springCloud + dubbo + nacos 的一个示例  配了2 个星期了。。。。

**Comment by haoyann** [comment]
使用 `spring-cloud-dubbo`，如果采用应用级别注册`dubbo-admin`还不支持。

**Comment by waxJava2615** [comment]
> 使用 `spring-cloud-dubbo`，如果采用应用级别注册`dubbo-admin`还不支持。

按照你所说，我把配置换成
dubbo:
  registry:
    address: nacos://${nacos.address}:${nacos.port}
dubbo-admin后台也看不到服务列表；
dubbo-admin配置,group namespace username password都配置了,而且dubbo-admin后台配置文件中都能冲NACOS中同步dubbo.properties这个配置文件
![image](https://user-images.githubusercontent.com/56405898/129124107-5c9aee5e-dafe-476f-b434-675dfce0c068.png)

NACOS中dubbo-admin的dubbo.properties配置：
![image](https://user-images.githubusercontent.com/56405898/129124339-e7ae609a-13d4-4aaa-98ae-9def5ad91bfb.png)

即使 我把元数据中心切换为ZK ，dubbo-admin后台服务列表还是空

**Comment by haoyann** [comment]
@waxJava2615 感谢你提供的信息，当前注册中心和元数据中心地址从远程配置中心获取有点问题，所以导致了这个BUG。可以参考一下这里的改动 #796。
