### ISSUE TITLE
Dubbo-admin服务测试问题

### ISSUE THREAD

**Issue by xieyucan** [apache/dubbo-admin#794]
入门小白请教大神关于dubbo-admin的问题，dubbo-admin服务测试功能不能用，代码逻辑看的不是很明白。
前言，注册配置中心使用nacos。启动nacos版本2.0.0、dubbo-admin版本最新develop、dubbo-provider服务dubbo版本2.7.7。
1. nacos服务列表如下：
![nacos](https://user-images.githubusercontent.com/20358819/128127561-26ea8ee1-a4d0-4983-9442-65d3cb22a6aa.png)

2. nacos服务详情如下：
![image](https://user-images.githubusercontent.com/20358819/128127685-5fefa0bf-21da-4c1d-89b6-371b93cb918a.png)

3. dubbo-admin服务查询，可以查询到相关服务如下：
![image](https://user-images.githubusercontent.com/20358819/128127730-b42f77f7-db91-4101-bf83-7c74d945709c.png)

4. dubbo-admin服务测试，通过服务名搜索服务功能如下：
![image](https://user-images.githubusercontent.com/20358819/128127779-69770346-ff3a-467d-95a2-91eb65a01583.png)

5. dubbo-admin服务测试，搜索逻辑如下：
5.1 获取provider服务相关信息，跟踪可以看到已经获取到了provider包括元数据等相关信息，如下：
![image](https://user-images.githubusercontent.com/20358819/128127942-ea0eb2c3-cf11-4206-9eb4-8c7e672455d4.png)
5.2 此处又去nacos上获取配置信息，疑问是这里是要获取元信息还是获取配置信息？
![image](https://user-images.githubusercontent.com/20358819/128127970-f5322d04-1483-4001-82e3-bbfd6e9d796e.png)
![image](https://user-images.githubusercontent.com/20358819/128128047-1c198a12-03d6-4216-967f-cda42216d272.png)
5.3 默认情况配置中没有数据，这里的metadata自然是取不到的
![image](https://user-images.githubusercontent.com/20358819/128128724-915740a1-d1ef-4412-a05e-c9645426e7fd.png)

疑问：
1. 这个逻辑是要我们把服务的元数据在拷贝一份到配置信息里面吗？
2. 个人觉得服务相关的信息直接从实例详情中取更合理一些，不清楚此处额外的从配置中获取相关的元信息是怎么考虑的？
3. 如果要放一份到配置中，配置中存放的数据的数据结构是怎么样的，有没有相关文档？

请大神指教🙏🏻

**Comment by haoyann** [comment]
@xieyucan 请问你 `dubbo` 版本是多少?

**Comment by xieyucan** [comment]
@haoyann  dubbo版本2.7.7

**Comment by haoyann** [comment]
请配置元数据中心的地址 `dubbo.metadata-report.address =`

**Comment by xieyucan** [comment]
感谢。
