### ISSUE TITLE
Does dubbo-monitor consider data collection asynchronously?

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo-admin#8]
alibaba/dubbo#1212, we should track this issue here.

**Comment by KeRan213539** [comment]
apache/dubbo#1212  should be talking about the problem of collection. How should admin deal with it?

**Comment by KeRan213539** [comment]
Sorry, because you didn't reply for a long time, we will close this PR first.
Please feel free to reopen it if you have any question.
