### ISSUE TITLE
dubbo-admin change log level error

### ISSUE THREAD

**Issue by cheng0571** [apache/dubbo-admin#80]
![image](https://user-images.githubusercontent.com/30223515/43703257-d04e1fe6-998e-11e8-9711-d54decb06f79.png)
system.management->logs->change.log.level 

![image](https://user-images.githubusercontent.com/30223515/43703247-c3c88e78-998e-11e8-9068-9066b2d013fd.png)

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
