### ISSUE TITLE
dubbo-admin无法查询到Nacos上的服务

### ISSUE THREAD

**Issue by yannick1991** [apache/dubbo-admin#803]
![image](https://user-images.githubusercontent.com/50813679/130026358-263f1494-8782-4fde-b2dd-c0d15e8f368e.png)
admin版本为develop-for-dubbo-3.x
![image](https://user-images.githubusercontent.com/50813679/130026582-e2148c45-e15b-4eec-8848-8f37618e0c84.png)
发现服务名不会带providers 等前缀，会自动过滤掉

**Comment by haoyann** [comment]
你 dubbo 是什么版本，nacos 的地址是怎么配置的。

**Comment by yannick1991** [comment]
> 你 dubbo 是什么版本，nacos 的地址是怎么配置的。

dubbo版本是 2.7.8
配置nacos的方式 是按照admin项目里的示例，配置的  nacos://地址:端口

**Comment by haoyann** [comment]
有指定 group 吗，需要配置对应的 group。
https://github.com/apache/dubbo-admin/blob/fc377e803ae49a564439b7e3c88a5e71da9d3b1c/dubbo-admin-server/src/main/resources/application.properties#L23-L27

**Comment by yannick1991** [comment]
> 有指定 group 吗，需要配置对应的 group。
> https://github.com/apache/dubbo-admin/blob/fc377e803ae49a564439b7e3c88a5e71da9d3b1c/dubbo-admin-server/src/main/resources/application.properties#L23-L27

admin.registry.address=nacos://172.165.197.25:9999?group=DEFAULT_GROUP&namespace=dev
admin.config-center=nacos://172.165.197.25:9999?group=dubbo
admin.metadata-report.address=nacos://172.165.197.25:9999?group=dubbo
这是我的配置
 
NacosRegistry的getAllServiceNames()方法可以查询到服务，服务名不带  providers这个前缀，会被filterData过滤掉。我打断点看到的是这样。
![Uploading image.png…]()

**Comment by haoyann** [comment]
@yannick1991 nacos 上注册的服务可以截图吗？注册上去的服务都是会带有 providers 的前缀的。
![image](https://user-images.githubusercontent.com/43994656/130172107-0d9efc6a-23b0-4368-985a-a50e4fda9644.png)

**Comment by yannick1991** [comment]
> @yannick1991 nacos 上注册的服务可以截图吗？注册上去的服务都是会带有 providers 的前缀的。
> ![image](https://user-images.githubusercontent.com/43994656/130172107-0d9efc6a-23b0-4368-985a-a50e4fda9644.png)

![image](https://user-images.githubusercontent.com/50813679/130172352-1f982317-e909-402d-afb8-1243192dcf6b.png)

**Comment by yannick1991** [comment]
> > @yannick1991 nacos 上注册的服务可以截图吗？注册上去的服务都是会带有 providers 的前缀的。
> > ![image](https://user-images.githubusercontent.com/43994656/130172107-0d9efc6a-23b0-4368-985a-a50e4fda9644.png)
> 
> ![image](https://user-images.githubusercontent.com/50813679/130172352-1f982317-e909-402d-afb8-1243192dcf6b.png)

我这跟你还不一样。。。

**Comment by haoyann** [comment]
你用的什么框架，dubbo-3.0 还是 spring-cloud-dubbo？

**Comment by yannick1991** [comment]
> 你用的什么框架，dubbo-3.0 还是 spring-cloud-dubbo？

spring-cloud-dubbo

**Comment by yannick1991** [comment]
@haoyann 会跟我们的nacos版本有关吗 我们的nacos版本1.3.2  是不是低了

**Comment by haoyann** [comment]
> @haoyann 会跟我们的nacos版本有关吗 我们的nacos版本1.3.2 是不是低了

使用 spring-cloud-dubbo，如果采用应用级别注册dubbo-admin还不支持。

**Comment by yannick1991** [comment]
@haoyann 不好意思 这个我没配过，可以配置服务级别注册吗

**Comment by yannick1991** [comment]
@haoyann 还是说  spring-cloud-dubbo 就只能是 应用级别注册?

**Comment by haoyann** [comment]
注册地址使用这个
```
dubbo:
registry:
address: nacos://${nacos.address}:${nacos.port}
```

**Comment by yannick1991** [comment]
> 注册地址使用这个
> 
> ```
> dubbo:
> registry:
> address: nacos://${nacos.address}:${nacos.port}
> ```

这样写  还可以区分namespace吗？我试了下 服务都在public下

**Comment by yannick1991** [comment]
> 注册地址使用这个
> 
> ```
> dubbo:
> registry:
> address: nacos://${nacos.address}:${nacos.port}
> ```

我试了下  确实可以，请问这样配置 是否dubbo.cloud.subscribed-services  就不再需要了

**Comment by yannick1991** [comment]
> 注册地址使用这个
> 
> ```
> dubbo:
> registry:
> address: nacos://${nacos.address}:${nacos.port}
> ```
![image](https://user-images.githubusercontent.com/50813679/130188941-84c05a7f-c76a-423a-a13b-38f4abc3cbaa.png)

这样写 会在配置列表中生成很多  服务的信息 ，方法我知道了，希望后面dubbo-admin可以做一些应用级别的注册支持。

**Comment by yannick1991** [comment]
@haoyann 非常感谢您的支持
