### ISSUE TITLE
dubbo-admin 使用java -jar启动出现循环依赖的错误

### ISSUE THREAD

**Issue by kiwi-field** [apache/dubbo-admin#821]
dubbo-admin使用java -jar启动报错，报循环依赖的错误, 
dubbo-admin版本 0.3.0 
zookeeper版本 3.3.3

![image](https://user-images.githubusercontent.com/30741355/133234756-ac279ebb-c9a9-4689-960b-341fc2f1bb68.png)

**Comment by kiwi-field** [comment]
用idea分别运行dubbo-admin-server 和dubbo-admin-ui没有问题

**Comment by horizonzy** [comment]
fixed by #823
