### ISSUE TITLE
the configuration file dubbo.properties do not work

### ISSUE THREAD

**Issue by keepongjl** [apache/dubbo-admin#83]
I hava config the **dubbo.properties** 
dubbo.registry.address=zookeeper://192.168.84.134:7763
bug it is not work
the dubbo-monitor can not start
 cat the log file dubbo-monitor-simple.log 
the message is
 Opening socket connection to server 127.0.0.1/127.0.0.1:2181.

**Comment by keepongjl** [comment]
I edit the project dubbo-monitor-simple dubbo.properties
and then mvn package
it work
......

**Comment by nope-J** [comment]
i have the same problem, did you fix it out?

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
