### ISSUE TITLE
目前是不支持nacos2.0.3版本吗？

### ISSUE THREAD

**Issue by raindayzhou** [apache/dubbo-admin#831]
大佬们，问一下目前是不支持nacos2.0.3版本吗？develop打开看服务列表是空的

**Comment by haoyann** [comment]
现在是支持 nacos 2.0 的，你提供的信息太少了。请贴出上下文信息，比如 dubbo 版本、admin 版本 和 配置信息。

**Comment by haoyann** [comment]
使用的是 `spring.cloud.alibaba.dubbo` 框架吗，现在并不支持 `spring.cloud.alibaba.dubbo` 的应用级发现。

**Comment by raindayzhou** [comment]
是的，谢谢大佬

**Comment by Roger0917** [comment]
> 使用的是 `spring.cloud.alibaba.dubbo` 框架吗，现在并不支持 `spring.cloud.alibaba.dubbo` 的应用级发现。

目前有考虑下个版本支持spring.cloud.alibaba.dubbo的应用级发现吗

**Comment by hongtongliang** [comment]
目前有考虑下个版本支持spring.cloud.alibaba.dubbo的应用级发现吗

**Comment by chywx** [comment]
目前有考虑下个版本支持spring.cloud.alibaba.dubbo的应用级发现吗
