### ISSUE TITLE
redis作为注册时，当提供者或者消费者异常（比如被KILL掉后），admin界面并没有更新其状态，redis数据库中的数据都已经没有了

### ISSUE THREAD

**Issue by zxf527** [apache/dubbo-admin#84]
添加提供者或消费者服务列表可以及时更新；但但提供者或消费者挂掉后却不能及时更新状态

**Comment by zhuSilence** [comment]
The same as this issue.

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
