### ISSUE TITLE
How to configure `zookeeper` ACL information in `docker compose`?

### ISSUE THREAD

**Issue by linghengqian** [apache/dubbo-admin#848]
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo Admin version: 0.3.0
* Registry center detail (type and version): zookeeper3.7.0
* Operating System version: The version that comes with Docker images
* Java version: The version that comes with Docker images

### Steps to reproduce this issue

1. This issue is related to https://github.com/apache/dubbo-admin/issues/404 . But in `dubbo-admin 0.3.0`, I did not see a configuration like this.
2. My idea is to configure the `ACL` authentication of `digest` on the root node of `zookeeper`. But I don't know how to configure it in the `environment` of `dubbo-admin`.
3. In https://github.com/apache/dubbo-admin/issues/825 , it is mentioned that `environment` can be configured under docker compose, but I did not see the relevant information of ACL verification.

**Comment by haoyann** [comment]
Try using the following configuration.
```
admin.registry.address=zookeeper://127.0.0.1:2181?username=xxx&password
admin.config-center=zookeeper://127.0.0.1:2181?username=xxx&password
admin.metadata-report.address=zookeeper://127.0.0.1:2181?username=xxx&password
```

**Comment by linghengqian** [comment]
> Try using the following configuration.
> 
> ```
> admin.registry.address=zookeeper://127.0.0.1:2181?username=xxx&password
> admin.config-center=zookeeper://127.0.0.1:2181?username=xxx&password
> admin.metadata-report.address=zookeeper://127.0.0.1:2181?username=xxx&password
> ```

Thank you for your answer.
