### ISSUE TITLE
LDAP auth. support for dubbo-admin

### ISSUE THREAD

**Issue by yjqg6666** [apache/dubbo-admin#85]
As the title.
Initial issue is apache/incubator-dubbo#1965

**Comment by nzomkxia** [comment]
thanks, Do you have any further solution?

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
