### ISSUE TITLE
使用dubbo-admin的疑惑 注册来源

### ISSUE THREAD

**Issue by QQ-ing** [apache/dubbo-admin#852]
hi ,dubbo-admin 0.3.0 的服务查询，其结果有一个注册来源，分为：接口级别和应用级别，我想问下他们之间有啥区别吗？或者哪里有说明文档的可以帮忙提供一下吗？

**Comment by haoyann** [comment]
是 dubbo 3.0 提供的新的服务发现，具体可以看这个文档 https://dubbo.apache.org/zh/docs/concepts/service-discovery/ ，dubbo-admin 的功能使用并没有什么不同。

**Comment by QQ-ing** [comment]
好的，谢谢大佬！我先去学习学习
