### ISSUE TITLE
服务统计功能无效

### ISSUE THREAD

**Issue by aaa489** [apache/dubbo-admin#853]
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo Admin version: 0.3.0
* Registry center detail (type and version): zookeeper
* Operating System version: windows
* Java version: 1.8
* Dubbo version: 2.7.12

### Steps to reproduce this issue

1. 服务端配置了metrics配置，配置如下：
![image](https://user-images.githubusercontent.com/23420362/143980850-36aea859-7dd3-48af-8f53-8bde3c550454.png)
2. 启用了MetricsFilter
![image](https://user-images.githubusercontent.com/23420362/143981103-2e5c4be7-00a0-4c7e-9f01-74d9983796d6.png)
3. 客户端向服务端发一次请求，触发MetricsService注册
4. dubbo admin上输入服务ip进行查询
![image](https://user-images.githubusercontent.com/23420362/143981425-aa03cb03-6e4b-4456-a3eb-77b82b1dd4f6.png)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

可以正常查询结果返回

### Actual Result

出错，报Service not found xxx错误

### 问题定位
大概看了下源码，dubbo admin是需要远程调用MetricsService的getMetricsByGroup接口来获取服务统计信息，而MetricsService是在MetricsFilter中创建并注册的，所以需要先消费端发起一次调用促进生成，但是MetricsFilter中暴露了MetricsService到本地之后，并没有注册到ApplicationModel的ServiceRepository，正常注册是有的，如下
![image](https://user-images.githubusercontent.com/23420362/143981972-b8e59e96-e81d-4d91-af9d-997968b1cbfd.png)
在dubbo admin发起远程调用的时候，服务端接收到之后会先进行decode，在过程中会取ApplicationModel的ServiceRepository查一下是否存在对应服务的key，也就是MetricsService
![image](https://user-images.githubusercontent.com/23420362/143982142-9f97c6f8-f7ee-43ef-9832-25d624806003.png)
正是因为在MetricsFilter中暴露的时候没有注册到ApplicationModel的ServiceRepository，所以这里查不到，也就抛出了Service not found的异常

**Comment by KeRan213539** [comment]
这应该是 dubbo 侧的问题, 请将issue提到[dubbo主仓库那边](https://github.com/apache/dubbo/issues)?

**Comment by aaa489** [comment]
待会儿提到那边去，只是想了解下：当时开发服务统计功能并且release的时候，这个没测过吗？我看到网上有些人说服务统计可用唯独缺少线程池统计，不知道如何做到？

**Comment by KeRan213539** [comment]
换个版本试试?我之前测试过2.7.8是可用的

**Comment by Leme34** [comment]
我用的Dubbo是2.7.18，对应最高可用dubbo-amin版本为0.3.0，摸着源码自己改好了，有完整的本地运行demo，供大家参考，详见https://github.com/Leme34/dubbo-spi-demo/tree/master/dubbo-admin
![1708596086266](https://github.com/apache/dubbo-admin/assets/32232194/f3fd2eb4-408d-4c2d-b667-8a2de7292706)
