### ISSUE TITLE
有计划支持JDK 11吗

### ISSUE THREAD

**Issue by ivancxj** [apache/dubbo-admin#862]
目前我们线上服务器全部都是jdk 11，但好像dubbo-admin还只能用在jdk 8，请问有计划支持或者有解决方案吗

**Comment by haoyann** [comment]
可以使用 11 试一下。

**Comment by chen796916** [comment]
> 

jdk11在解析token的时候会抛找不到javax.xml.bind.DatatypeConverter的异常

**Comment by haoyann** [comment]
> > 可以使用 11 试一下。
> 
> jdk11在解析token的时候会抛找不到javax.xml.bind.DatatypeConverter的异常

添加依赖试一下。
```
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.0</version>
</dependency>
```

**Comment by haoyann** [comment]
closed by #886.
