### ISSUE TITLE
How use dubbo-admin statistics?

### ISSUE THREAD

**Issue by mawer111** [apache/dubbo-admin#869]
- [x] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo Admin version: 3.0.0
* Registry center detail (type and version): nacos 2.0.3
* Operating System version: Linux
* Java version: 1.8

### Steps to reproduce this issue

1. How use dubbo statistics features? I'm not found any config manual to use statistics.I use a simple demo dubbo provider and consumer with sping bean config mode,My bean is define in a xml config file.Maybe need a <dubbo:metrics> bean?

Any manual can help?

**Comment by inotgaoshou** [comment]
同问，谢谢

**Comment by mawer111** [comment]
@inotgaoshou https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-metrics try this.
