### ISSUE TITLE
dubbo-monitor-simple2.0没有监控到服务

### ISSUE THREAD

**Issue by mark-wk** [apache/dubbo-admin#88]
zookeeper用的是远程服务器，地址已经在配置文件配置过，执行的start.sh脚本，不知道为何显示的注册地址是localhost/127.0.0.1:2181，且检测不到远程注册的服务。
--

**Comment by nope-J** [comment]
解决了吗？我这边也遇到同样的问题

**Comment by lesineyzk** [comment]
一样，我这边测试也是监控不到，服务可以注册进去调用，但监控中心没有显示
[zk: localhost:2181(CONNECTED) 0] ls /
[dubbo, codingsky, zookeeper]
[zk: localhost:2181(CONNECTED) 1] ls /dubbo
[com.alibaba.dubbo.monitor.MonitorService, com.codingsky.service.TestService]
[zk: localhost:2181(CONNECTED) 2] ls /dubbo/com.codingsky.service.TestService
[consumers, configurators, routers, providers]

**Comment by KeRan213539** [comment]
Sorry, because this issue was raised very early, we have closed it temporarily. You can verify whether this problem still exists in the latest code of the develop branch. If this problem still exists, please reopen it at any time.
