### ISSUE TITLE
点击服务测试后，这个服务会在服务查询列表消失

### ISSUE THREAD

**Issue by chenjjl** [apache/dubbo-admin#891]
每次调用服务测试后都会reference.destory()，造成了点击服务测试后在服务查询列表里这个服务就消失了。

**Comment by haoyann** [comment]
应该不是这个原因，`reference.destory()` 只是销毁的泛化调用的客户端，不会影响服务列表。

**Comment by chenjjl** [comment]
测试发现reference.destory()会生成protocol为empty的url，导致RegistryServerSync#notify()监听到后把该服务从列表里移除了
<img width="1152" alt="截屏2022-05-13 11 00 24" src="https://user-images.githubusercontent.com/50745778/168202863-7b6ca5dc-53c5-4934-a342-409b7d84fe6e.png">
dubbo3.0.8是修复了这个问题吗？

**Comment by haoyann** [comment]
3.0.8 解决的是这个问题 https://github.com/apache/dubbo/issues/8654，你说的这个问题我再看看。

**Comment by haoyann** [comment]
确实有这个问题存在, 升级到 dubbo 3.0.8 之后 #903  已经解决了.
