### ISSUE TITLE
dubbo-go作为服务的consumer，却被认为成了provider，造成dubbo-admin显示无元数据信息，无法调用。

### ISSUE THREAD

**Issue by sherlock-art** [apache/dubbo-admin#908]
环境 K8s
dubbo-admin版本 基于master最新分支0.3.0
注册中心 zk
java版本1.8_261

**问题描述及现象**
dubbo-go作为xxx服务的consumer时，会注册到dubbo-admin上，dubbo-admin却认为它是provider，点击对应的服务测试后，真正的provider信息被覆盖，服务不能再被调用
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/66151680/175762112-7d0fc884-7469-441a-bfe1-bbd6cceb4835.png">
![image](https://user-images.githubusercontent.com/66151680/175762121-7a885c1d-3aa0-448d-87e4-f208b47e3c77.png)
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/66151680/175762134-65ef9f80-fdb3-4c33-8b15-af3ce430eb4c.png">
![image](https://user-images.githubusercontent.com/66151680/175762151-38b515d6-0451-4b16-a95c-fc1caa45d92a.png)

查看源码猜测原因：
1. 消费者语言为go，用的是dubbo-go，从url中看到registry url 中 side为consumer
consumer:///com.xxx.service.api.CustomerApi?app.version=1.0.0&application=xxx&async=false&bean.name=ServiceBean:com.xxx.service.api.CustomerApi:1.0.0&check=false&cluster=failover&environment=environment&generic=false&group=group&interface=com.xxx.service.api.CustomerApi&ip=10.46.19.116&loadbalance=loadbalance&methods.findCustomerByTeamUid.loadbalance=methods.findCustomerByTeamUid.loadbalance&methods.findCustomerByTeamUid.retries=1&methods.findCustomerByTeamUid.sticky=false&methods.getPrimaryServiceGroupByCustomerUid.loadbalance=methods.getPrimaryServiceGroupByCustomerUid.loadbalance&methods.getPrimaryServiceGroupByCustomerUid.retries=1&methods.getPrimaryServiceGroupByCustomerUid.sticky=false&module=dubbo-go client&name=xxx&organization=dubbo.io&owner=owner&protocol=rest&provided-by=provided-by&reference.filter=cshutdown&registry.role=0&release=dubbo-golang-1.5.6&retries=retries&side=consumer&sticky=false&version=1.0.0

2. 由于RegistryServerSync#notify()这里的逻辑，如果category为null则默认为provider，把消费者变成了生产者，覆盖了真正的生产者
![image](https://user-images.githubusercontent.com/66151680/175761352-a7cd219f-2a1e-4cc1-8255-06bc8681f4fe.png)

3.源码处增加side的判断
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/66151680/175940896-410f1b80-4718-4cc2-83c2-9aed0c04fac9.png">

请问这样做，是否合理呢，如果合理，麻烦采纳一下，谢谢！

**Comment by haoyann** [comment]
可以这样，欢迎贡献代码.

**Comment by sherl0ckLiu** [comment]
PR已提。

**Comment by sherl0ckLiu** [comment]
PR已提

**Comment by haoyann** [comment]
Close by #910
