### ISSUE TITLE
通过docker启动存在消费者ip为空的情况

### ISSUE THREAD

**Issue by xiangzz159** [apache/dubbo-admin#912]
- [ ] I have searched the [issues](https://github.com/apache/dubbo-admin/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [REAMDE](https://github.com/apache/dubbo-admin/blob/develop/README.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo Admin version: 0.4.0
* Registry center detail (type and version): zookeeper:3.5.5
* Operating System version: MacOS 10.15.7
* Java version: 1.8.0_231

### Steps to reproduce this issue

1. 通过docker启动服务 images：apache/dubbo-admin:0.4.0
2. 服务查询接口 - 接口详情 - 消费者列表为空
3. 检查ZK，该接口消费者列表不为空
<img width="428" alt="image" src="https://user-images.githubusercontent.com/16982273/176871842-1389fe6c-5e88-495b-a2d5-594e54aac082.png">

4. 排查发现是数据通知的时候consumer ip为空
![1](https://user-images.githubusercontent.com/16982273/176871910-034802b3-0dda-4541-b359-fc17d0adaeb9.png)
![2](https://user-images.githubusercontent.com/16982273/176871928-ff388f6f-e7b4-4532-be8d-ec4c41ac9c1a.png)

5. 服务实例都是通过云原生启动

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
see https://dubbo.apache.org/zh/docs3-building/java-sdk/advanced-features-and-usage/others/set-host/

**Comment by xiangzz159** [comment]
在这里的时候还有ip信息
![image](https://user-images.githubusercontent.com/16982273/176984436-549568b4-7eee-4ceb-a223-13a6ae5c5811.png)

但到了这里就没有了
![image](https://user-images.githubusercontent.com/16982273/176984607-d58dc238-3f50-406d-94ab-bd74b1bd3ca3.png)

**Comment by xiangzz159** [comment]
dubbo版本升级到3.0.9解决

**Comment by sherl0ckLiu** [comment]
> dubbo版本升级到3.0.9解决

亲测有效，有两个问题想请教一下：
1.为啥只有用docker启动时ip才为null
2.怎么知道要升级dubbo到3.0.9呢（解决问题的过程）

**Comment by xiangzz159** [comment]
> > dubbo版本升级到3.0.9解决
> 
> 亲测有效，有两个问题想请教一下： 1.为啥只有用docker启动时ip才为null 2.怎么知道要升级dubbo到3.0.9呢（解决问题的过程）

<img width="1441" alt="image" src="https://user-images.githubusercontent.com/16982273/177928812-d1d582c4-b0ca-4aa7-a8c2-ec1b14b42b48.png">

3.0.8使用了私有变量path
![企业微信截图_aca3a5f4-c704-47c0-8eeb-55f010c09d9f](https://user-images.githubusercontent.com/16982273/177928915-40133cb5-c1f1-4d25-a588-be358e3463b1.png)

3.0.9使用了传递变量
<img width="1167" alt="企业微信截图_d96be9ec-2ced-4920-9e60-f4158bd4e021" src="https://user-images.githubusercontent.com/16982273/177928958-4c840461-4518-4bd4-88d3-0a202d68008f.png">

**Comment by xiangzz159** [comment]
不止Docker会出现这种情况，通过IDE启动项目的时候也会出现这种情况
